### ISSUE TITLE
[Feature] Add Table Export Option

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#1000]
Currently there is a function for exporting the table:
https://github.com/AssemblyScript/assemblyscript/blob/20e882c88586e79b4038e47d013aa7ddd2c692b5/src/module.ts#L1069)

but no way to access this through the cli API.

**Comment by jtenner** [comment]
Context:

Aspect could benefit from inspecting the function table at testing time to get the name of the function and display it. 

Yes. This causes binaryen to avoid optimizing and Inlining other functions.

No. This isn't game breaking for aspect users because it's used for debugging purposes (and aspect by default doesn't use any optimizations at all anyway)

**Comment by jtenner** [comment]
Suggestion:

- add `--exportTable` flag
