### ISSUE TITLE
Runtime error in ~lib/rt/tlsf/reallocateBlock

### ISSUE THREAD

**Issue by vladimir-tikhonov** [AssemblyScript/assemblyscript#1036]
Link to webassembly studio: https://webassembly.studio/?f=q145eekpct

Code:
```typescript
export function willFail(): void {
    const b = buildB();
    b.a.bs.push( b );
}

function buildB(): B {
    const a = new A();
    return new B( a );
}

export class A {
    public bs: B[] = [];
}

@unmanaged
export class B {
    public a: A;

    public constructor( a: A ) {
        this.a = a;
    }
}
```

Stack trace:
```
RuntimeError: unreachable
    at ~lib/rt/tlsf/reallocateBlock
    at ~lib/rt/tlsf/__realloc
    at ~lib/array/ensureSize
    at ~lib/array/Array<assembly/index/B>#push
```

**Comment by MaxGraey** [comment]
It seems this happened only when class B is unmanaged

**Comment by dcodeIO** [comment]
I think what happens there is on

```js
function buildB(): B {
    const a = new A();
    return new B( a );
}
```

since `B` is unmanaged, it doesn't retain a reference to `a` so the instance of `A` is immediately free'd again after that, looking like this internally:

```js
function buildB(): B {
    const a = __retain(new A());
    let ret = new B( a );
    __release(a);
    return ret;
}
```

In general, mixing unmanaged and managed classes like that requires taking special care of retaining everything that goes into unmanaged land as long as unmanaged land is alive.

**Comment by vladimir-tikhonov** [comment]
@dcodeIO Got it, I've thought that `@unmanaged` affects only references of the class itself, and its fields will still `__retain`ed / `__release`d during assignment. 
Btw, `__retain`, `__release` and `__free` aren't in the definitions ats

**Comment by dcodeIO** [comment]
Yeah, the unmanaged stuff is kinda unwieldy and I usually try to not encourage people too much to use it, since that usually raises at least two new questions for every question answered.

> Btw, __retain, __release and __free aren't in the definitions atm

Stdlib, which this is primarily intended for, gets the types by means of `// <reference path="path/to/std/assembly/rt/index.d.ts" />` where all of this lives. Not really part of the public stdlib API.

**Comment by dcodeIO** [comment]
To add to that: One could argue that `@unmanaged` shouldn't be in std definitions then as well. Perhaps we can separate the internal API to another "official" .d.ts we ship for everyone interested, so it at least becomes easier to have proper types for that. Like an `assemblyscript-rt.d.ts`.
