### ISSUE TITLE
AS runtime should export the __free() method

### ISSUE THREAD

**Issue by thomasfischl** [AssemblyScript/assemblyscript#1041]
If you allocate an AS memory in JS with the **__alloc()** function, there is no way to release this memory block afterwards, because the **__free()** method is not exported via the runtime. 

### Suggested Solution: 
https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/rt/index-full.ts

`export { __alloc, __free } from "rt/tlsf";`

### Use Case:
My use case is, that I want to process images in WA. For that reason, I create in JS an Uint8ClampedArray array with a memory buffer from the AS runtime for the image. I copy the imageData pixel array and use this the pointer to the array as parameter for the WA function. After the processing is done, I copy the memory back and want to release the dynamic allocated memory.

```javascript
function callASFunction(imageData: ImageData) {
  const imageDataLength = imageData.width * imageData.height * 4;
  const imageMemory = wasmModule.instance.exports.__alloc(imageDataLength + 1)
  let wasmImageData = new Uint8ClampedArray(module.instance.exports.memory.buffer, imageMemory, imageDataLength)

  wasmImageData.set(imageData.data);

  // calculate a grayscale image with AS funciton
  module.instance.exports.grayscaleFilterSimd(imageMemory, imageDataLength);

  const newImage = new ImageData(wasmImageData, imageData.width, imageData.height);

  // this method is missing 
  module.instance.exports.__free(imageMemory);
  
  return newImage;
}
```

**Comment by thomasfischl** [comment]
A workaround for the moment is, that I export the **__free()** function myself.

`export { __free } from "rt/tlsf";`

**Comment by dcodeIO** [comment]
The recommended way to deal with lifetimes of managed objects is to count references, since manually freeing something can break the runtime if the object is still referenced from somewhere else. In the simplest form this can be done by an `ptr = __retain(__alloc(size, 0))` which makes a managed ArrayBuffer with a reference count of 1, and once you are done with it call `__release(ptr)`. This is roughly equivalent to freeing the object, but also accounts for the possibility of the buffer still being alive within the module, where the module would release it once it's no longer used.

**Comment by thomasfischl** [comment]
The `__release(ptr)` function was also my first intention, but I got an unreadable error. It was not clear to me, that I need to call the `__retain(ptr)` function by myself. My understanding was, that the `__retain(ptr)` function is called automatically from the `__alloc()` function and you only need to call the `__retain(ptr)` function, if you want to add another ref to this memory block.

After checking the code now, I saw, that the functions are coming from the two modules `rt/tlsf`and `rt/pure`. 

Wouldn't it a good idea, to expose a function from the `rt/pure` module like  `__safe_alloc()`, which combines the `__alloc()` and the `__retain()` function?

**Comment by MaxGraey** [comment]
Yeah expose something like ` __safe_alloc` or `__retained_alloc` will be great also in point of performance because we reduce one expensive interop call

**Comment by dcodeIO** [comment]
Iirc we have been talking about switching to allocating with RC=1 a while ago, but this hasn't been pursued since then. The current state is mostly from how this evolved, with a use case for allocating something and freeing right away in stdlib if we need some scratch space for a managed object that will never make it to managed land. Would prefer to first look into that instead of adding another API method.
