### ISSUE TITLE
Passing arrays?

### ISSUE THREAD

**Issue by togekk** [AssemblyScript/assemblyscript#105]
Hi,
I noticed that arrays can only been manipulated within wasm modules when I'm using the playground. Is it possible to pass arrays (either typed or dynamic ones) to and from javascript at the moment? Thanks!

**Comment by dcodeIO** [comment]
Indirectly, yes. WASM has only four basic types for now (i32, i64, f32, f64), and what you are passing to/from JS is the offset (i32) of the [array structure in memory](https://github.com/AssemblyScript/assemblyscript/wiki/Memory-Layout-&-Management#arrays).

**Comment by dcodeIO** [comment]
Depends, calling in and out of WASM has some overhead as well. If performance is a concern, I'd suggest to create a typed array view of the memory region in question on the JS side, and use that to read respectively write the values.

**Comment by togekk** [comment]
I've managed to pass my Float64Array to and from WASM. Another question is, I couldn't get the correct offset through bitwise operators as [here](https://github.com/AssemblyScript/assemblyscript/blob/e049e72171e7bfc28af326a786ba508c09a6ecb8/lib/loader/README.md) mentioned. So I had to manually put a value in the first of the array from WASM to get the offset from JS. For example, "34" for  Int32Array and "17" for Float64Array. But these offsets didn't seem to be regular, so I had to do the test again when creating a new array. Moreover, when I re-declared the same array name with a different length, the offset shifted again so while writing on the WASM side, I couldn't get the corresponding array from JS anymore. For the normal arrays it got more complex. Is there any simple and safe to do this? Thanks!

**Comment by dcodeIO** [comment]
When returning a `Float64Array` from WASM, the JS-side receives the offset of the respective structure in memory. Arrays have one additional level of indirection to their backing ArrayBuffer, as [explained here](https://github.com/AssemblyScript/assemblyscript/wiki/Memory-Layout-&-Management#arrays), so that might be where the random offset you described comes from. What you want to do there is to read the `buffer` offset first, and then use that to access the data of the backing buffer.

**Comment by togekk** [comment]
I used console.log to see my ArrayBuffer after I inserted 2 Float64Array arrays. After "36" they're all zero. The offsets of these arrays are "17" and "27", but I didn't see any of them in the ArrayBuffer? Or I'm not sure if it's ArrayBuffer?

```
Float64Array(8192)
​
[0…99]
​​
0: 0
1: 1.2461269196343288e-306
2: 1.1125688450857216e-306
3: 1.602190346336971e-306
4: 8.622619559087905e-308
5: 9.346070741559093e-307
6: 1.602208000948219e-306
7: 1.7801215608693142e-306
8: 5.9415882204e-313
9: 8.0109788924021e-307
10: 1.7802084774853345e-306
11: 7.565998073254955e-307
12: 1.6021849125978852e-306
13: 8.011087537446835e-307
14: 9.346002835725136e-307
15: 1.6912136703862707e-306
16: 2e-322
17: 0
18: 0
19: 0
20: 0
21: 0
22: 0
23: 0
24: 6.3e-322
25: 2e-322
26: 4e-323
27: 8274.8330078125
28: 9834.966796875
29: 4e-323
30: 8e-323
31: 1
32: 1
33: 0
34: 1.186e-321
35: 8e-323
36: 0
```

**Comment by togekk** [comment]
I've found out a safer way now. Here are the steps:

1. On the JS side, use allocate_memory to get every pointer for every items, and write them into an array:

```
for (let i = 0; i < length; i++)
       ptr_array[i] = module.allocate_memory(1);
```

2. Write the item values into the ArrayBuffer using the bitwise operators:

```
array.forEach((item, index) => {
       const ptr = ptr_array[index];
       module.F64[ptr >>> 3] = item;
});
```

3. Send the starting pointer while calling all the WASM function:

```
module.myFunction( ptr_array[0], arg2, arg3..... );
```

4. On the WASM side, get the first pointer, the following items are certain bytes after it depending on which kind of type array you're using. For example, Float64Array uses 8 bytes each. It's decribed [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays) well. So we use "load" and "store" function to read and write the memory.

```
for (let i = ptr; i < ptr + len * 8; i += 8) {
       let item = load<f64>(i);
       item = item / 300;
       store<f64>(i, item);
}
```

5. Back on the JS side, simply use the bitwise operators again to retrieve those items:

```
console.log(module.F64[ptr_array[index] >>> 3]);
```

And all is done! Remember to free/reset memory after that. Use 3 typed arrays in my project without any problem :)

But I still couldn't figure out how to get the typed array offset from the WASM side. The document link provided looks like the HEX code from the WASM file? I still have no luck to find "17" and "27" these 2 offsets as mentioned above...

**Comment by dcodeIO** [comment]
More precisely, what you get back is a pointer to the `Float64Array` structure in WASM memory. That structure does not contain the actual data, but another pointer to an `ArrayBuffer` that holds the data. So, the first 4 bytes at the offset returned are the pointer to the ArrayBuffer, the next 4 bytes is the byteOffset into that ArrayBuffer, the next 4 bytes is the byteLength of that ArrayBuffer. What you'd want to do is:

1. Retrieve the pointer to the `Float64Array` by returning it from WASM
2. Read the first 4 bytes at that pointer to obtain the pointer to the ArrayBuffer, bytes 4-7 to obtain the byteOffset and bytes 8-11 to obtain the byteLength (the last is only necessary if you'd like to do a range check).
3. Read the value from the address of the ArrayBuffer (as obtained in step 2). The data of an ArrayBuffer starts at offset 8, then add byteOffset + index * elementByteSize (here: 8).

**Float64Array**

| Offset | Data
|------|---
| 0..3   | .buffer -> ArrayBuffer
| 4..7   | .byteOffset
| 8..11 | .byteLength

**ArrayBuffer**

| Offset | Data
|-------|------
| 0..3   | .byteLength
| 4..7   | zero due to alignment
| 8...    | DATA

**Comment by togekk** [comment]
So all the pointers must be retrieved from I32 array view (or create an Int32Array view on your own), and the code will look like this:

WASM side: 

```
export function show_array(): Float64Array {
  let a: Float64Array = new Float64Array(5);
  a[0] = 99.88;
  a[1] = 88.77;
  a[2] = 77.66;
  a[3] = 66.55;
  a[4] = 55.44;
  return a;
}
```

JS side:

```
const array_buffer = fs.readFileSync(__dirname + "/build/optimized.wasm");
...

const arr_ptr = myModule.show_array();
console.log(arr_ptr);
const buffer_ptr = myModule.I32[arr_ptr >>> 2];
const byteOffset = myModule.I32[arr_ptr + 4 >>> 2];
const byteLength = myModule.I32[arr_ptr + 8 >>> 2];
const elementByteSize = 8;

for (let i = 8; i < 8 + byteOffset + byteLength; i += byteOffset + elementByteSize)
    console.log(myModule.F64[buffer_ptr + i >> 3]);
```

Thanks for all the detailed answers, now it all works :)

**Comment by msbasanth** [comment]
@togekk  even I have similar issue where I need to pass and return a u8[].

When converted I got,
`function decodeRLE(encodedBuffer: u32): u32;`

even though I have my AS function signature,
`function decodeRLE(encodedBuffer: u8[]): u8[]`

How can I retrieve the argument from passed array pointer? Similarly how can I retrieve full u8[] (UInt8Array) from returned array pointer. 

I tried the snippet you shared I am getting module.I32 as 'undefined'. Should I do something to get I32 array view?

**Comment by inkeliz** [comment]
It's not possible to get the pointer of Buffer pointer directly in AssemblyScript? I would like to do something like:

```
let x = new Uint8Array(1000);

export function Pointer() : u32 {
return pointerOf(x[0])
}
```

In that case the host can receive the pointer and manipulate the memory directly?

```

**Comment by MaxGraey** [comment]
```ts
let x = new Uint8Array(1000);

export function Pointer() : usize {
  return x.dataStart;
}
```
