### ISSUE TITLE
NodeList and other Arrays ?

### ISSUE THREAD

**Issue by WebReflection** [AssemblyScript/assemblyscript#106]
First of all, thanks for this tool!

Hopefully not a silly issue but I was trying to export a module capable of dealing with DOM nodes too. AFAIK TypeScript has NodeList and NodeListOf and it wouldn't complain with HTMLElement classes but here I'm incapable of passing either a static collection of Node elements or even just one, since all types I've tried produce errors.

Will this ever even possibly work? Best Regards

**Comment by dcodeIO** [comment]
The only thing that can be passed to and from wasm at the moment are the webassembly types `i32` (`i64` cannot be passed directly), `f32` and `f64` - all becoming a `number` on the JS side. Everything else is constructed of these types, like strings and (the memory of) classes. The [loader component](https://github.com/AssemblyScript/loader/blob/master/src/index.ts) has some utility to work with the most prominent higher level types, but it's not possible to exchange arbitrary references, i.e. to DOM nodes, at this point.

Things will become more interesting once the [GC spec](https://github.com/WebAssembly/gc) lands because it will not only provide a garbage collector, effectively eliminating the need to ship a memory management runtime, but also initial js/wasm interchangeable types like arrays and classes that can be exchanged by reference.

**Comment by WebReflection** [comment]
So, if I understand correctly, the `ArrayAccessor` is the generic interface I'm looking for, correct?

About the GC, do you know of any ETA for that? Thanks!

**Comment by dcodeIO** [comment]
> So, if I understand correctly, the `ArrayAccessor` is the generic interface I'm looking for, correct?

Let's say you have the following simple program:

```ts
let a: int[] = [ 1, 2 3];

export function main(): int[] {
  return a;
}
```

You'd then, on the JS side, call `main`, which returns the array's address in memory and use that with the loader:

```js
let ptr = exports.main();
let arr = memory.array.get(ptr);
for (let i = 0; i < arr.length; ++i) {
  console.log(memory.int.get(arr.base + i * 4));
}
// should print 1, 2, 3
```

[This test case](https://github.com/AssemblyScript/assemblyscript/blob/master/tests/interop/arrayliteral.test.ts) does something similar.

> About the GC, do you know of any ETA for that?

Unfortunately not, would also love to know that.

**Comment by WebReflection** [comment]
oh, I see. It's to expose, not to "import", fair enough.

Thank you!
