### ISSUE TITLE
How would C++ libraries work?

### ISSUE THREAD

**Issue by opiepj** [AssemblyScript/assemblyscript#116]
If I wanted to use AssemblyScript with libraries like OpenGL or GLFW, would that be possible? How would that work?

**Comment by RangerMauve** [comment]
You'd need to have libraries that would work as WASM modules to interoperate with them, I'd assume.

**Comment by nidin** [comment]
WebGL will fullfill functionalities of OpenGL

**Comment by jdanford** [comment]
@opiepj Emscripten, the toolchain that allows languages like C++ and AssemblyScript to compile to WebAssembly/asm.js, provides a runtime environment for compatibility with the libraries you mentioned, among others. From the [Emscripten wiki](http://kripken.github.io/emscripten-site/docs/introducing_emscripten/about_emscripten.html):

> Emscripten support for portable C/C++ code is fairly comprehensive. Support for the C standard library, C++ standard library, C++ exceptions, etc. is very good. SDL support is sufficient to run quite a lot of code. OpenGL support in Emscripten support is excellent for OpenGL ES 2.0-type code, and acceptable for other types.

Here are some resources:
[Emscripten Runtime Environment](http://kripken.github.io/emscripten-site/docs/porting/emscripten-runtime-environment.html)
[OpenGL support in Emscripten](http://kripken.github.io/emscripten-site/docs/porting/multimedia_and_graphics/OpenGL-support.html)
[Porting Examples and Demos](https://github.com/kripken/emscripten/wiki/Porting-Examples-and-Demos)

**Comment by opiepj** [comment]
Basically, would it require a preliminary step? Not sure if that helps if you wanted to import GLFW. But similar to Rust, you'd probably need to provide bindings.

**Comment by dcodeIO** [comment]
There haven't been any efforts in this direction, yet, but ultimately tooling should provide some means of linking multiple wasm binaries to one to solve issues like these. Regarding C++ specifically, it'll most likely help to have a C interface exported because that's easier to work with (no name mangling etc.). For example, the current memory management runtime is compiled from C which is then used as the base image of any generated modules that the AssemblyScript code can call. You'd then provide a .d.ts describing the interface, compile your AS program and link it to the other binary. Unfortunately, there's not really any reliable tooling for linking yet (besides Binaryen's wasm-merge, but that hasn't worked for me yet).

Nonetheless, remember that whatever you plan to link currently will most likely have to call into JS some way or another when using Web APIs like WebGL. From my experience, stuff compiled with emscripten has so much overhead size-wise, that creating a binding to WebGL in AssemblyScript itself should, at least at this point, be more efficient - certainly at the downside of having to reinvent the wheel.
