### ISSUE TITLE
Support Deno With Loader

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#1207]
This is a very easy change. All we need to do is switch to es module exports.

See: https://github.com/crabmusket/deno_assemblyscript_example

Any thoughts?

**Comment by MaxGraey** [comment]
Add `loader.mjs`?

**Comment by jtenner** [comment]
Should we have a module build process and switch the loader to Typescript?

**Comment by dcodeIO** [comment]
Some parts of the loader are a bit suboptimal to describe in TS, since it also does some dynamic magic here or there. In such cases I typically prefer to write it in JS right away, since porting to TS only adds complexity.

Should be possible to provide it in ES module form quite easily, though. Just expecting a bit of a hassle to make that a nice hybrid module to publish to npm. Last time I checked node and mjs/non-mjs still used to be unnecessarily painful, but I guess you guys are more up to date there than I am :)

**Comment by MaxGraey** [comment]
We could use [esm](https://github.com/standard-things/esm#getting-started) or use some simple and lightweight module which transform esm to cjs as build stage

**Comment by jtenner** [comment]
Bootstrapping the compiler here is a trivial task using the deno/std/node library. I believe there's a problem with the loader itself. Will have to look further.

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) as ESM support is now being tracked in https://github.com/AssemblyScript/assemblyscript/issues/1306, a more general issue also covering this one.
