### ISSUE TITLE
Expose ASTBuilder

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#1212]
Is it possible to expose the ASTBuilder class so that external projects can use it?

Could we add another project to the lib directory?

**Comment by jtenner** [comment]
@dcodeIO cam we expose this via the compiler interface in the `assemblyscript` package? I suppose this shouldn't be included in the compiler, because it's "extra", but it's definitely useful.

Potential solutions (not including everything in between):

1. Expose this via the primary assemblyscript package (easiest way to get this done)
2. Move to `lib` and make it a separate module which involves creating an additional build step

I will happily take responsibility for this improvement, but I would like guidance before I start development.
