### ISSUE TITLE
[Feature Request] Atomic properties

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#1253]
Proposed mechanism for this: `@atomic` decorator

Given the following class example:

```ts
class A {
  @atomic b: i32 = 0;
}

// should be the equivalent of writing the following code

class A {
  private _b: i32 = 0;
  public get b(): i32 {
   return atomic.load<i32>(changetype<usize>(this), offsetof<A>("_b"));
  }
  public set b(value: i32) {
   return atomic.store<i32>(changetype<usize>(this), value, offsetof<A>("_b"));
  }
}
```

**Comment by dcodeIO** [comment]
To add to the discussion on Slack: I think we'll have to decide how to approach threading in general. For instance, the mechanism proposed here is a bit like Java's `synchronized`, which also covers methods etc., but we'd first have to be sure that this is what we want over something like `postMessage` and friends.

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) because the suggestion made here doesn't seem feasible as-is, respectively a more general discussion about how we'd like to approach threads is necessary first. At this point in time, my expectation is that we'll ultimately end up deciding for a more JS-like approach to threading, mimicking workers and postMessage, while leaving the ins and outs of low-level locking to those interested in implementing manual locking.
