### ISSUE TITLE
Question: __retain/__allocArray large arrays performance?

### ISSUE THREAD

**Issue by jfuehner** [AssemblyScript/assemblyscript#1285]
Hi! I'm new to assemblyscript and am looking for some guidance. Curious if perhaps there is a more efficient/performant way to accomplish my use-case...

Say I have some really large standard arrays...

```
    let positions = randomArray(10000000);
    let lineColors = randomArray(positions.length*4);
    let lineWidths = randomArray(positions.length*1);
    let fillColors = randomArray(positions.length*4);
```

Would there be a more performant way to create typed arrays that could be passed to a WASM function for processing? The below `__retain`/`__allocArray` code takes a good deal of execution time...

```
    const [fillColorsPtr, lineColorsPtr, lineWidthsPtr, positionsPtr] = await Promise.all([
        exports.__retain(exports.__allocArray(exports.INT8ARRAY_ID, fillColors)),
        exports.__retain(exports.__allocArray(exports.INT8ARRAY_ID, lineColors)),
        exports.__retain(exports.__allocArray(exports.INT8ARRAY_ID, lineWidths)),
        exports.__retain(exports.__allocArray(exports.FLOAT64ARRAY_ID, positions))
    ])

    exports.process(fillColorsPtr, lineColorsPtr, lineWidthsPtr, positionsPtr);
```

Hoping there may be a better way to pass the arrays to the process function. Thanks!

**Comment by dcodeIO** [comment]
Fiddled around with this a bit, and what I'm seeing is that the `randomArray` calls in JS (made a guess on the implementation) take 4.5 seconds due to the sheer size apparently, with the `__allocArray` calls taking about 480ms.

Assuming you are aware of the JS slowdown and mostly interested in the 480ms contributed by the loader, most of this is from the `Uint8Array#set`s within, accounting for 203ms, 199ms, 49ms, 21ms for the arrays, again looking like a JS bottleneck.

Since this appears to be a JS bottleneck, I tried to move construction of the arrays from JS to Wasm:

```ts
export const INT8ARRAY_ID = idof<Int8Array>();
export const FLOAT64ARRAY_ID = idof<Float64Array>();

function randomArray<T>(size: i32): T[] {
  var arr = new Array<T>(size);
  for (let i = 0; i < size; ++i) {
    unchecked(arr[i] = <T>(Math.random() * 8));
  }
  return arr;
}

export var positions = randomArray<f64>(10000000);
export var lineColors = randomArray<i8>(positions.length * 4);
export var lineWidths = randomArray<i8>(positions.length * 1);
export var fillColors = randomArray<i8>(positions.length * 4);
```

which is already much better and accounts for 465ms including instantiation of the module. On the JS side, one can then use `exports.__getArrayView(exports.positions)` to get a live view without any copying, which is pretty fast (3ms).

**Comment by MaxGraey** [comment]
I just wonder why you use `await Promise.all` for synchronous calls?

**Comment by jfuehner** [comment]
@dcodeIO thanks for taking a look! In my real world use-case the random arrays will actually be coming from the server.

So really I was more so focused on `__retain/__alloc` area since that seems to take the bulk of the time. Any ideas there on how to get them to WASM faster? Essentially, after getting them into WASM they will be processed and a subset of them arrays will be returned...

@MaxGraey I actually saw a slight performance improvement wrapping the synchronous calls in `Promise.all`

**Comment by dcodeIO** [comment]
> __retain/__alloc area [...] seem to take the bulk of the time

That's a misconception. Both `__retain` and `__alloc` are more or less constant time and don't become slower for what's perceived as larger inputs. Looks like what you need there is a way to make the JS part more efficient, for instance by transferring the arrays as binary ArrayBuffers, i.e. using a `fetch` -> `Response` -> `arrayBuffer -> new XYArray(arrayBuffer, 0, len)` -> `__allocArray(ID, xyArray)`.

**Comment by jfuehner** [comment]
@decode I do initially receive the JSON object via web socket as an ArrayBuffer.

I could theoretically pass that ArrayBuffer to WASM but then I would be faced with converting that ArrayBuffer to JSON. Probably not a JSON.parse equivalent in assemblyscript, right?

**Comment by dcodeIO** [comment]
Passing large numeric arrays like these as JSON will most likely always remain a bottleneck, simply because JSON involves conversion from/to text. The best you can do I think is to eliminate the JSON layer, and transfer the arrays as binary directly, i.e. a raw WebSocket ArrayBuffer message in this case.
