### ISSUE TITLE
Side project idea: asm.js annotation front-end

### ISSUE THREAD

**Issue by Artoria2e5** [AssemblyScript/assemblyscript#1355]
`asm.js` had a few ways to [annotate types using JS syntax](http://asmjs.org/spec/latest/#annotations). It may be interesting to see a program that parses these things into valid assemblyscript. Example rules are:

* `(expr) | 0` is type `i32`
* `+(expr)` is type `f64`

(Do note that these fules do *not* apply to AssemblyScript proper, where number types other than i32 and f64 can be produced by these expressions. `fround` is still there though.)

**Comment by MaxGraey** [comment]
`asm.js` is subset which should be compatible with ordinal javascript but could run more performant in some browsers like Mozilla. Btw `asm.js` also more close to bytecode rather than to high level source of code and was (and still) target from languages as C/C++. So it doens't make sense support such syntax due to we have complete type system borrowed from TypeScript.
