### ISSUE TITLE
asinit produces invalid package.json dependencies

### ISSUE THREAD

**Issue by RReverser** [AssemblyScript/assemblyscript#1357]
Running `npx asinit` in an empty folder creates a `package.json` like following:

```json
{
  "scripts": {
    "asbuild:untouched": "asc assembly/index.ts -b build/untouched.wasm -t build/untouched.wat --sourceMap --debug",
    "asbuild:optimized": "asc assembly/index.ts -b build/optimized.wasm -t build/optimized.wat --sourceMap --optimize",
    "asbuild": "npm run asbuild:untouched && npm run asbuild:optimized",
    "test": "node tests"
  },
  "dependencies": {
    "@assemblyscript/loader": "^0.12.4"
  },
  "devDependencies": {
    "assemblyscript": "^0.12.4"
  }
}
```

However, it fails at `npm install` phase, because the latest version of `@assemblyscript/loader` is only `0.10.1`.

**Comment by MaxGraey** [comment]
Can confirm.
@dcodeIO will be great also install `"@assemblyscript/loader"` via `asinit` by default

**Comment by dcodeIO** [comment]
Turns out that the switch to semantic-release didn't cover publishing the loader, so it hasn't been published since then. The PR above should fix this.

In the meantime, requiring `assemblyscript/lib/loader` instead of `@assemblyscript/loader` does work as well, but isn't a standalone package. Once the above PR is merged, the next release should include the loader again. 0 UTC.

**Comment by dcodeIO** [comment]
The loader has been published again meanwhile. Version 0.12.5.
