### ISSUE TITLE
Add change log

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#1493]
Currently to see all of the new changes you have to read releases page, which is less than optimal since they are spaced out and are multiple pages.  It would be nice to auto-generate a change log so that you can read a document instead making it more easily searchable and compact.

**Comment by MaxGraey** [comment]
We use `semantic-release` which have ability to do this:
https://github.com/semantic-release/release-notes-generator

So PR welcomed)

**Comment by dcodeIO** [comment]
With the switch to [aspublish](https://github.com/AssemblyScript/assemblyscript/pull/1519) the [release notes](https://github.com/AssemblyScript/assemblyscript/releases) became a little more dense with less noise, but it's still not a single document. Since that's not semantic-release anymore, making a changelog document would probably need, during `aspublish`:

* Find `CHANGELOG.md` in current working directory
* Prepend the release notes to it if it exists, otherwise skip
* If not skipped, push the updated file back to GH

For that I guess we'd also want a way to skip CI on changelog-only pushes.
