### ISSUE TITLE
Local variable names lost while debugging

### ISSUE THREAD

**Issue by letmaik** [AssemblyScript/assemblyscript#1496]
Local variables appear as `var0`, `var1`, etc. in the debugger (Chrome).

**Comment by MaxGraey** [comment]
That's expected. Unfortunately browsers can't do this. WebAssembly has proposal which should fix this:
https://github.com/WebAssembly/extended-name-section/blob/master/proposals/extended-name-section/Overview.md

**Comment by letmaik** [comment]
Hm, Chrome supports DWARF, and binaryen seems to have support for it (https://github.com/WebAssembly/binaryen/issues/2400). Is this a limitation of binaryen then? Or could it be that asc doesn't enable DWARF output in binaryen?

**Comment by letmaik** [comment]
See also https://github.com/emscripten-core/emscripten/issues/8934#issuecomment-676595678.

**Comment by AGreat1** [comment]
If you'll pardon me, I would like this issue reopened. I'm really interested in debugging a wasm module compiled with asc in a runtime other than the browser, like wasmtime. It's not clear to me whether asc emits DWARF info then? So would it be debuggable with gdb or lldb? @MaxGraey any thoughts?

**Comment by MaxGraey** [comment]
AssemblyScript doesn't emit DWARF yet. Actually it should provide by Binaryen which has some limited support of DWARF but only for transform DWARF debug info and also in very limit way (many optimization passes doesn't handle dwarf data and turned off when dwarf section present).

**Comment by saulecabrera** [comment]
@MaxGraey do the optimization passes that are turned off for DWARF, actually prevent us from exploring this avenue at all? This [comment](https://github.com/WebAssembly/binaryen/issues/2400#issuecomment-600817386) actually hints the opposite of what you're suggesting, so I wonder if it's worth it giving this a try and if it works maybe adding DWARF support as experimental to the compiler. 

One of the main reasons why I think that having support for debug symbols is important is because observability and debugging of WASM modules in large, server-side systems is not feasible. Ideally, we could take advantage of the DWARF support in FF/Chrome and build tools to allow developers to debug their modules locally, which would give them an extra layer of confidence when testing their modules. 

The other option is to stick with source maps, which are definitely better than dealing with raw traps. 

@dcodeIO I'm curious to know what's your take on this.

**Comment by dcodeIO** [comment]
Generating a DWARF section is definitely something I'd like to explore but don't know when I'll get to it. Information I have from the Binaryen side of things is that, in the current state, Binaryen only implements the pieces of DWARF that are relevant to pipe it through, and it may not be feasible to add a Binaryen API to more conveniently *generate* DWARF yet, so if we want that we'd need to generate a "line table" (that one was mentioned) etc. on our own and attach the debug section with `BinaryenAddCustomSection`.

A little less sophisticated alternative that may be a good start however may be to utilize Binaryen's C API to set local names (that is available already but we don't use it yet), which I so far attempted but found that 

1. ASC often uses shared locals anyway (unless declared with `var`), so it is only useful to some extent
2. Binaryen's optimization passes seem to confuse local names, leading to wrong ordering, which we'd have to fix unless we only do it in debug builds where we don't run any optimizations

Help appreciated :)

**Comment by MaxGraey** [comment]
> This comment actually hints the opposite of what you're suggesting, so I wonder if it's worth it giving this a try and if it works maybe adding DWARF support as experimental to the compiler.

Check source code for optimization pipeline:
https://github.com/WebAssembly/binaryen/blob/main/src/passes/pass.cpp#L394

As you can see all passes have `addIfNoDWARFIssues` name due to many passes don't preserve some debug data [properly](https://github.com/WebAssembly/binaryen/blob/main/src/passes/pass.cpp#L389)

**Comment by saulecabrera** [comment]
Thanks for the detailed explanation @dcodeIO. And apologies @MaxGraey I misunderstood your comment. 

Just to clarify a bit my point, yeah I only meant exploring this for `debug` builds. For optimized builds, at least for our use case would be a bit trickier, I don't think that we want debug symbols in optimized modules. If we ever do that, we'll probably want the symbols [detached](https://yurydelendik.github.io/webassembly-dwarf/#external-DWARF) from the module. 

In any case, thanks for the pointers, I think this summarizes the state of DWARF support pretty well.

**Comment by AGreat1** [comment]
Do you think this is something that would be happening in the near future, or something that is like more than a year down the road?

**Comment by MaxGraey** [comment]
I guess this issue should be fixed in `0.21.x` with this https://github.com/AssemblyScript/assemblyscript/pull/2437
