### ISSUE TITLE
support for indexed access with unknown strings

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#1556]
#640 was closed

**Comment by dcodeIO** [comment]
Iiuc, `this[someString]` with `someString` being any string and `this` not being a `Map` is too dynamic to be efficient since it loses ahead-of-time type information and uses names that do not exist at runtime anymore. Implementing this would require extensive reflection information to be shipped with each binary and perf will probably degrade into interpreter land. Hence not expecting this to be supported anytime soon.

**Comment by trusktr** [comment]
Ah ok.

What if for non-`this` use cases, AS treats `const o: {[k: string]: SomeType} = {}` identical to `const o = new Map<string, SomeType>()`, and `o[someString]` the same as `o.get(someString)`?

It would be compatible with TS/JS, while still having the performance of a `Map`.

**Comment by dcodeIO** [comment]
Maps already have non-standard indexed access overloads, so one can do `myMap[myKey]` on them. Edge cases, again, though, because if a key does not exist it traps just as `.get` does. Other than that I'd prefer not to conflate these concepts for now, as it may well be that anonymous object types will be needed for something else in the future, like multi value types, or that extending such a type will have other unexpected edge cases again, i.e. that `.get` and `.set` etc. exist which wouldn't be the case in TS.

In general I understand the craving for more nice things, I just worry that going overboard with these will paint us into a corner before we even got the chance to get started. Take for instance the attempts so far to build a sophisticated GC runtime on top of just the Wasm MVP. Prime example of a critical mistake.

**Comment by dcodeIO** [comment]
I think there is more to it than that. These kinds of objects will be much slower than in jitted JS, somewhat defeating the purpose of using Wasm. Making this explicit, by requiring folks to use a `Map`, may be a more reasonable approach at least while we do not know whether this will ever become fast. Also, anonymous object types like `{ a: i32, b: string }` may become useful one day to implement an actual Wasm feature, like named multi-value returns from functions, e.g.

```ts
function foo(): { a: i32, b: string } {
  var a = 1;
  var b = "a";
  return { a, b };
}
var { a, b } = foo(); // must deconstruct
```

but I can't tell for sure yet where this will go. Would prefer to leave our options open than to add a premature feature we'll regret and may as well be implemented by other, more type-safe, and faster, means, even though it needs more explicit code for now.
