### ISSUE TITLE
Support for arithmetic between different types.

### ISSUE THREAD

**Issue by synxroform** [AssemblyScript/assemblyscript#1576]
It seems strange that i can't add i32 to f32, or vice versa without explicit type casting. Can compiler just insert type casting instructions for me automatically ?

**Comment by MaxGraey** [comment]
That's not strange at all. f32 can't be safely (without lost precision or dynamic range) cast to i32 and vise versa. In all strongly typed languages which I know this can't be done implicitly. It can't be done even in JS=) `x | 0` (cast float to int), `Math.fround(x)` (cast int to 32-bit float).

**Comment by dcodeIO** [comment]
In case it helps, there's also [this table](https://www.assemblyscript.org/types.html#type-rules) within the docs outlining which assignments may be implicit, and which ones must be explicit to be safe. i32 -> f64 for instance is allowed without an explicit cast, since the full range of values representable in the source type can be represented by the target type.

**Comment by synxroform** [comment]
Oh, thank you. Didn't work with statically typed languages long time. Python definitely spoiled me.
