### ISSUE TITLE
Compiler flag for changing page size

### ISSUE THREAD

**Issue by void4** [AssemblyScript/assemblyscript#1601]
Non-standard compliant/modified WebAssembly implementations may have a memory page size different to the standard 64k. Could there be an asc compiler flag that let's one work with that?

**Comment by dcodeIO** [comment]
Should be possible I guess, with respective changes to the TLSF implementation [around here](https://github.com/AssemblyScript/assemblyscript/blob/bef5bea8ac665ce64200e12ba81b9e2c69ba64cb/std/assembly/rt/tlsf.ts#L440-L448). Perhaps a constant `ASC_PAGESIZE_BITS` that defaults to `16` and can be overridden with `--use ASC_PAGESIZE_BITS=X` so it doesn't even require its own option.

**Comment by 00ff0000red** [comment]
> Should be possible I guess, with respective changes to the TLSF implementation [around here](https://github.com/AssemblyScript/assemblyscript/blob/bef5bea8ac665ce64200e12ba81b9e2c69ba64cb/std/assembly/rt/tlsf.ts#L440-L448). Perhaps a constant `ASC_PAGEALIGN` that defaults to `16` and can be overridden with `--use ASC_PAGEALIGN=X` so it doesn't even require its own option.

They appear to be talking about page sizes, not page alignment.
WebAssembly has no control over page sizing, nor page alignment, page alignment is expected to be aligned to 16 bytes by the implementor, and the very idea of WebAssembly is broken if an implementor chooses to use a different page size other than 0x10000 bye per page. Wasm is supposed to be a portable, open-source, binary format that essentially fulfills Java's old "write once, run anywhere" slogan. If the implementor chooses to not properly support Wasm, on purpose, then they simple can't run Wasm, there's not much more to it.

Now, your specific request is not possible, because WebAssembly has no control over how large each individual page is, the format only defines *how many* pages that the implementor should allocate, and a maximum cap for the memory to grow too.

Example using .wat format:
```wat
(memory 3)
```
The binary format should contain a LEB encoded integer 3, and the runtime/implementor is expected to allocate 3 * 0x10000 bytes before executing the compiled code.

Hopefully, this has helped to explain why this cannot be done.
If I have been misinformed, please feel free to correct me.

**Comment by dcodeIO** [comment]
I understand that a non-standard page size is certainly an uncommon request, and I'd also question the standardness here, but since a language really only does `pages << 16` at a couple places in the dynamic memory allocator to translate from pages to bytes it would be trivial to make that `16` configurable with something like `--use`, a catch-all option for uncommon things like these.

**Comment by 00ff0000red** [comment]
I highly doubt that a non-standard Wasm runtime like this will appear, a more likely scenario is that someone did their math wrong and messed up their JiT 😄
But, there was a mention from one of the Wasm spec members about non-page sized allocations, for modules that don't need the full 64kb of memory, I can't find it, but if it ever happens, then this issue will definitely need to be solved.
