### ISSUE TITLE
Is it safe to compile untrusted inputs?

### ISSUE THREAD

**Issue by void4** [AssemblyScript/assemblyscript#1604]
While *running* compiled AssemblyScript programs in a WebAssembly is safe, does the same apply to using the asc compiler on the source code? I want to create a website that, like webassembly.studio, lets users submit their own programs to the server, where they are compiled. But I'm not sure if this is safe.

**Comment by dcodeIO** [comment]
The compiler does not fully execute the code it emits before emitting it, and the modules it emits are subject to the typical Wasm sandbox when instantiated. So that should be safe I guess as long as special care is taken to not provide the final instantiated module any unsafe imports. And, ofc, given that there isn't some sort of vulnerability somewhere.

On the project's [website](https://www.assemblyscript.org), we are running the compiler right in the browser for example.

**Comment by void4** [comment]
So the _result_ of the compilation process will probably be safe, that I understand. But could a maliciously formed input crash/subvert the compiler during compilation? I guess the only way to make sure is to really run it in a (WebAssembly?) sandbox itself...

**Comment by dcodeIO** [comment]
Specifically crafted inputs can result in long compilation times of course, lead to termination due to overflowing the stack or exhaustion of available memory. So yeah, anything that may crash a browser tab is a concern also on the server.

The compiler itself compiles to both JS with `tsc` and Wasm with `asc`. It's "portable AssemblyScript". For the latter to be actually useful you may want to wait for https://github.com/AssemblyScript/assemblyscript/pull/1559 to land.

**Comment by void4** [comment]
> So the result of the compilation process will probably be safe, that I understand. But could a maliciously formed input crash/subvert the compiler during compilation? I guess the only way to make sure is to really run it in a sandbox itself...

Makes sense.

> The compiler itself compiles to both JS with tsc and Wasm with asc. It's "portable AssemblyScript". For the latter to be actually useful you may want to wait for #1559 to land.

That's pretty cool!

Wasm interpreters like [pywasm](https://github.com/mohanson/pywasm) or [life](https://github.com/perlin-network/life) allow one to limit the number of instruction steps that are executed and memory allocation, this may incur some overhead but assure safety: https://github.com/mohanson/pywasm/blob/master/examples/cycle.py

So I might use this approach :)

Thank you
