### ISSUE TITLE
Support class expressions

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#161]
Like this:

```ts
const Vec2 = class {
  constructor (
    public x: i32 = 0,
    public y: i32 = 0
  ) {}
}
const vec = new Vec2();
```

For now this cause compiler (parsing?) to infinite execution.

**Comment by dcodeIO** [comment]
One issue I see here is that a class, which is essentially just a collection of functions, is not represented by any value at runtime yet, so there is nothing to assign to a variable. Maybe the class id one day, but I don't know if a construct like that can be type checked statically because a variable might hold a reference to any class, preventing `new`ing it or calling its static methods in a type safe way.

**Comment by MaxGraey** [comment]
Yah, that's probably complicated implement this in way as JS does. But what if just for a start parse this properly and emit some errors for as long as complete support this?

**Comment by dcodeIO** [comment]
Just tried the code sample above. It gives quite a few parse errors because it doesn't understand it yet, but it also doesn't result in an endless loop. Did I miss something?

**Comment by MaxGraey** [comment]
Yah, it seems this happening only in WebAssembly Studio

**Comment by dcodeIO** [comment]
There should be parser support for class expressions now. Can't be compiled, of course, but we can revisit this once there's something on the horizon that makes it feasible.

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) because it has been lingering for quite a while and hasn't been picked up, indicating that it's not overly important just yet. In general this would involve a virtual table for classes by id, again deferring to a virtual class tables, and that doesn't look too efficient.
