### ISSUE TITLE
Multi-value support?

### ISSUE THREAD

**Issue by CrimsonCodes0** [AssemblyScript/assemblyscript#1633]
The WebAssembly [multi-value proposal](https://github.com/WebAssembly/multi-value) has already been apart of the Wasm [finished-proposals](https://github.com/WebAssembly/proposals/blob/master/finished-proposals.md) for some time, yet I can't find any mention of how to use it in ASC, although Binaryen supports it, and AS is supposed to allow low-level control over the output Wasm, if I'm not mistaken.

I had edited a simple [Fibonnaci function implementation](https://github.com/AssemblyScript/assemblyscript/issues/162#issuecomment-403110513), into the following:

```ts
const SQRT5 = 2.23606797749979;
const C1 = 0.48121182505960347;
const C2 = -0.48121182505960336;

export function fib(n: f64): f64 {
  if (n <= 0) {
    return 0;
  }

  const temp = f64x2.mul(f64x2(C1, C2), f64x2.splat(n));

  const a = Math.exp( f64x2.extract_lane(temp, 0) );
  const b = Math.exp( f64x2.extract_lane(temp, 1) );

  return Math.round(
    (i32(n) & 1 ? a + b : a - b) * (1.0 / SQRT5)
  );
}
```

Regarding optimization, I checked the wat and noticed that the compiler was emitting two f64 locals, when it could've left the values on the stack, something more like the following:
```
local.get temp
f64x2.extract_lane 0
call Math.exp
local.get temp
f64x2.extract_lane 1
call Math.exp
local.get n
i32/f64
i32.const 1
i32.and
if (param f64 f64) (result f64)
    f64.add
else
    f64.sub
end
f64.const 1.0
global.get SQRT5
f64.div
f64.mul
call Math.round
return 
```

which should provide superior codegen in runtime VMs, while yielding size benefits.

There has been mention of waiting for Multi-value support for multiple things already, such as adding [nullable types](https://github.com/AssemblyScript/assemblyscript/issues/1410), among other things.

Is multi-value support is the plans already?

**Comment by MaxGraey** [comment]
> Is multi-value support is the plans already?
Yes. Will be used for tuples and nullable primitive types like `i32 | null`. But currently this not implemented

https://github.com/AssemblyScript/assemblyscript/wiki/Status-and-Roadmap

**Comment by 00ff0000red** [comment]
Tuples themselves don't need to use the multi-value proposal, they could be implemented more like how C variardic functions are, but otherwise it's great to hear that it's in the plans at least.

Do you have any preliminary idea of how one would write that pseudo-Wat in AS? Afaik, Binaryen doesn't do too well with multi-values, or at least not yet. should we expect ASC to optimize code to make use of it?

**Comment by MaxGraey** [comment]
> Tuples themselves don't need to use the multi-value proposal, they could be implemented more like how C variardic functions are

tuples can't only pass as arguments but also should return as result as multiple values. C / C++ use shadow stack for that but Wasm hasn't access to shadow stack, so it usually emulate. But multi-values much more efficient. See this for example:
https://godbolt.org/z/f9OIcq

**Comment by munrocket** [comment]
I am currently working on AssemblyScript WebAPI bindgen (.idl -> externref) and interested in multi-value support. According to my old benchmark it was major performance pitfall in AssemblyScript (#997, #1560). Also it seems that it fit to [idl-dictionaries](https://webidl.spec.whatwg.org/#idl-dictionaries) because it is literally struct/tuple.
