### ISSUE TITLE
AS emitting runtime casting for boolean=>i32; potential Binaryen bug?

### ISSUE THREAD

**Issue by CrimsonCodes0** [AssemblyScript/assemblyscript#1656]
[Editor link to AS source](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWImbm9Bc3NlcnQmbm9FeHBvcnRNZW1vcnkKZXhwb3J0IGZ1bmN0aW9uIHRlc3QxKHg6IGJvb2xlYW4pOiBpMzIgewogIHJldHVybiB4CiAgICA/IDEKICAgIDogMDsKfQoKZXhwb3J0IGZ1bmN0aW9uIHRlc3QyKHg6IGJvb2xlYW4pOiBpMzIgewogIHJldHVybiBzZWxlY3Q8aTMyPiggMSwgMCwgeCApOwp9CgpleHBvcnQgZnVuY3Rpb24gdGVzdDMoeDogYm9vbGVhbik6IHVzaXplIHsKICByZXR1cm4geAogICAgPyAxNgogICAgOiAwOwp9CgpleHBvcnQgZnVuY3Rpb24gdGVzdDQoeDogYm9vbGVhbik6IHVzaXplIHsKICByZXR1cm4geCAqIDE2Owp9CgpleHBvcnQgZnVuY3Rpb24gdGVzdDUoeDogYm9vbGVhbik6IHVzaXplIHsKICByZXR1cm4gKHggYXMgdXNpemUpIDw8IDQ7Cn0KIyFodG1sCjx0ZXh0YXJlYSBpZD0ib3V0cHV0IiBzdHlsZT0iaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJSIgcmVhZG9ubHk+PC90ZXh0YXJlYT4KPHNjcmlwdD4KbG9hZGVyLmluc3RhbnRpYXRlKG1vZHVsZV93YXNtLCB7IC8qIGltcG9ydHMgKi8gfSkKICAudGhlbigoeyBleHBvcnRzIH0pID0+IHsKICAgIGNvbnN0IG91dHB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKQogICAgZm9yIChsZXQgaSA9IDA7IGkgPD0gMTA7ICsraSkgewogICAgICBvdXRwdXQudmFsdWUgKz0gYGZpYigke2l9KSA9ICR7ZXhwb3J0cy5maWIoaSl9XG5gCiAgICB9CiAgfSkKPC9zY3JpcHQ+)

I found this while checking out https://github.com/AssemblyScript/assemblyscript/issues/103#issue-321386398.

This function:
```ts
export function test1(x: boolean): i32 {
  return x
    ? 1
    : 0;
}
```
is equivalent to `x as i32`. Because `boolean` is `0 | 1`, booleans are a subset of the range of an i32, so casting from boolean to i32 should not emit any runtime instructions, (as opposed to i32 => boolean).

Expected:
```wat
(func $module/test1 (param $0 i32) (result i32)
  local.get $0
)
```

Instead, I'm getting the following wat output:
```wat
(func $module/test1 (param $0 i32) (result i32)
  local.get $0
  i32.eqz
  i32.eqz
)
```
or
```wat
(func $module/test1 (param $0 i32) (result i32)
  local.get $0
  i32 const 0
  i32.ne
)
```

I want to immediately call this out as a binaryen compiler backend bug, but I'm wondering whether this could be an AS problem?
Maybe AS isn't providing enough information to the backend, such as `x` not being an i32, but instead being `0 | 1`?

(Tests 3-5 are all semanticially equivalent, and are somewhat related, yet not. I'll probably raise an issue with Binaryen later about those.)

**Comment by MaxGraey** [comment]
WebAssembly hasn't `i1` or `boolean` type. So internally when you write:
```ts
let x: boolean;
```
it actually:
```ts
let x: i32
```
for normalize `x` to `0 | 1` range you should apply two operations like `!!x` or `(eqz (eqz x))` or `x != 0`. Host may pass any value, not only `true` or `false`. That's why we need this. LLVM don't do this, I don't know why. Simple example how this may fail if not apply normalization input: https://webassembly.studio/?f=2jri8n6wbw9

**Comment by 00ff0000red** [comment]
Yes, I understand that at the ABI level, it's `let x: i32`, yet semanticially it is `let x: i32(0) | i32(1)`.
Is it assumed that the input will be invalid?

AssemblyScript shouldn't be able to call it without it being `true` or `false`.

Annoyingly, even this:
```ts
export function test1(x: boolean): i32 {
  return (x as i32) & 1;
}
```
emits the equivalent of
```wat
x != 0
```

As for why LLVM doesn't do this, it's likely because the C++ standard doesn't define booleans as containing anything other than 0 or 1, leaving invalid booleans as UB. Rust does the same, defines them as UB, and normalizes the input, mimicing AS's output.

Is this behavior limited to exported functions? The normalization is just extra code if it's occuring in internal functions.
