### ISSUE TITLE
`--transform` has different behavior.

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1695]
I write a simple transform but I have use `npx asc` to execute.
If run `asc` to execute it.
I got error:
```
FAILURE TypeError: Cannot redefine property: signbit
```

The lookup path is confusing me.

**Comment by dcodeIO** [comment]
Hmm, that looks like it originates here:

https://github.com/AssemblyScript/assemblyscript/blob/4ccda0b5c34e7a29bc111994088b99b8b4a418e9/std/portable/index.js#L353-L357

**Comment by willemneal** [comment]
@yjhmelody The issue here is that you are importing the library twice.  That is your transformer tries to import an `assemblyscript` that is different that called the transform.

I solved this in [`visitor-as`](https://github.com/willemneal/visitor-as) by "re-exporting" by just finding it in node's module cache.  So in your file, just `import {  } from "visitor-as/as"`.
