### ISSUE TITLE
Does assemblyscript have a filename extension without (.ts)

### ISSUE THREAD

**Issue by chooaya** [AssemblyScript/assemblyscript#1750]
typescript and accemblyscript in n some cases may be used in the same project, but with the extension (.ts) . People cannot tell the difference between typescript and accemblyscript . If there is a new filename extension(exp: **.asmts** ) for assemblyscript ,I think everyone will be happy.Thank you

**Comment by dcodeIO** [comment]
There is a discussion already to [consider a file extension other than .ts](https://github.com/AssemblyScript/assemblyscript/issues/1003) that may be of interest.

**Comment by chooaya** [comment]
> There is a discussion already to [consider a file extension other than .ts](https://github.com/AssemblyScript/assemblyscript/issues/1003) that may be of interest.

So just use this setting
{
  "files.associations": {
    "*.asmts": "typescript"
  }
}

"*.asmts" will be considered as typescript, Right?
Thank you very mush!!

**Comment by dcodeIO** [comment]
That's not necessarily enough, unfortunately. More information on the matter is available at the issue I linked, but the short version is that there is a compiler option to switch out the file extension considered by `asc`, but that mileage may very when the goal is also to import external packages, say via a package manager, since these may use different file extension and the implementation is not far enough along yet to account for this.
