### ISSUE TITLE
Support tuples as syntactic sugar for classes

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1778]
Hi, i find that `as` do not support tuple now. Is there any plan to support the feature ? Can tuples be simply implemented as syntactic sugar for classes ? If it doesn't work, what's the reason ?

**Comment by yjhmelody** [comment]
I mean that predefine tuple1 ... tuple32 like: 

```ts
class Tuple32<A1, A2 ... A32> { a1: A1; a2: A2 ... a32: A32} 
```

And then compile such [string, u32] to Tuple2<string, u32>.

**Comment by dcodeIO** [comment]
It is still an open question how we'd want to support Wasm's multi-value feature eventually, which closely relates to an eventual implementation of tuples and may in turn utilize the `[typeA, typeB]` notation. So we haven't used this notation yet to keep our options open, also because multi-value does not map exactly to what one would expect from TS tuples.
