### ISSUE TITLE
Calling an @inline `constructor` will cause validate error

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1820]
```
[wasm-validator error in function assembly/Result/Result<assembly/Bool/Bool,assembly/Bool/Bool>#constructor@varargs] unexpected false: call target must exist, on
(call $assembly/Result/Result<assembly/Bool/Bool,assembly/Bool/Bool>#constructor
 (local.get $0)
 (local.get $1)
 (local.get $2)
 (local.get $3)
)
FAILURE validate error
    at Object.main (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\cli\asc.js:876:23)
    at C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\bin\asc:19:47
```

**Comment by MaxGraey** [comment]
Could you show minimal example?

**Comment by yjhmelody** [comment]
```
@inline
export function instantiateZero<T>(): T {
    let t: T;
    if (isFloat(t)) {
        return 0;
    } else if (isInteger(t)) {
        return 0;
    } else if (isBoolean(t)) {
        return false;
    } else {
        return instantiate<T>();
    }
}

export class Result<O, E>{
    // it works when remove @inline 
    @inline
    constructor(
        protected readonly _ok: O,
        protected readonly _err: E,
        protected _is_err: bool = false
    ) {}

    static Ok<O, E>(ok: O): Result<O, E> {
        return new Result<O, E>(ok, instantiateZero<E>());
    }

    // ...
}

let res: Result<bool, string> = Result.Ok<bool, string>(true);
```

@MaxGraey

**Comment by MaxGraey** [comment]
Thanks!

**Comment by MaxGraey** [comment]
I reduced it to minimal example:
```ts
export class Test<E> { // Generic (2)
    // + @inline  (1)
    @inline constructor(protected foo: bool = false) {} // at least one optional param (3)
}

let res = new Test<i32>();
```

So error happening only when three requirements:
1) inline constructor
2) Generic class
3) At least one optional param in constructor

**Comment by dcodeIO** [comment]
Heh, this is quite a bunch of events leading to the issue here. You can add: (4) The class must be a module export

What happens is that the compiler inlines calls to the constructor, including omitted arguments, so neither the original constructor nor its varargs stub actually exists as a Wasm function. During finalization it then tries to ensure the module export, in turn triggering the varargs stub, but not the original, which was respectively would be inlined. That's the missing function seen in validation. Stubs cannot inline calls, though.

Still a little unclear to me how to approach this properly, with the simplest solution being a one-line fix (when making the stub export, also make the original, essentially ignoring `@inline`), and the most complex one going deep into stub logic.

**Comment by dcodeIO** [comment]
Turns out we already have the machinery to inline stuff into stubs in place nowadays :)
