### ISSUE TITLE
Add a decorator that annotates a method, function or class is exported to wasm

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1848]
Sometimes an as file provides lib API and can also be used as a wasm executable file, but at this time all export-modified objects will be exported, but the export section of wasm often does not allow or do not want redundant exports.

**Comment by dcodeIO** [comment]
There is indeed an ambiguity here, and I have lately been considering to remove exports of namespaces and classes altogether because of it. This would force everyone to explicitly export only functions one needs, using a wrapper on the top-level if necessary, like so:

```ts
namespace Foo {
  export function bar(): void {}
}

export function bar(): void {
  Foo.bar();
}
```

While it requires additional work, enforcing this would naturally map to Wasm exports and as a side-effect enforce the flexibility that is asked for here, if I understand correctly.
