### ISSUE TITLE
How to call gc.collect from AS code in 0.18?

### ISSUE THREAD

**Issue by AfflatusX** [AssemblyScript/assemblyscript#1882]
Hi - we recently upgraded AS version from 0.17 to 0.18. However, gc.collect() is not longer a valid API. We use minimal runtime and run GC manually from AS. What's the correct way to invoke it in 0.18?

**Comment by AfflatusX** [comment]
looks like I can call __collect() directly, but that function is not recognized by VSCode somehow (the code compiles/runs fine).

Is this something expected?

**Comment by dcodeIO** [comment]
With the minimal runtime, it is dangerous to call `__collect` from within the Wasm binary when the stack is not guaranteed to be unwound, since there is no shadow stack. The expectation there is that one would call it externally occasionally, in a code path not directly or indirectly called from Wasm. When using the incremental runtime, it is unnecessary to call it most of the time.

**Comment by AfflatusX** [comment]
I see, that makes sense.
