### ISSUE TITLE
What type does enum get compiled into?

### ISSUE THREAD

**Issue by AfflatusX** [AssemblyScript/assemblyscript#1883]
Given an enum:

enum A {
  OPTION_A = 0;
  OPTION_B = 1;
}

does that enum get compiled into an i32 type? (so it takes 4 bytes memory)

**Comment by dcodeIO** [comment]
Yes, values of type `A` are `i32`s.

**Comment by AfflatusX** [comment]
I see, curious if it's possible to add a type annotation to force it compiles to other types (u8 for example) to save memory? most enums only has less than a dozen members - or is there a technical reason this cannot be done?

(this is low pri since it only applies to really memory constrained environment)

**Comment by dcodeIO** [comment]
We haven't yet done this because it's not necessarily TS-y, so yeah, I guess low prio is a good assessment :) Currently one could just always `<u8>A.OPTION_A` or use a type mixed with a namespace, [like so](https://github.com/AssemblyScript/assemblyscript/blob/8a280c4a0ddfb0de6de65fc86c1b04a6a7425f78/src/module.ts#L33-L49).

**Comment by AfflatusX** [comment]
cool, that's what I thought! thanks for the explaination, closing!
