### ISSUE TITLE
Implementing Interface functions throw duplicate identifier

### ISSUE THREAD

**Issue by MKHenson** [AssemblyScript/assemblyscript#1897]
Hi there, I believe I found a bug. I've read through the documentation and searched the internet to see if I'm misunderstanding something. However nothing seems to jump out to me as incorrect. 

**Steps to reproduce**

- Go to AS playground or create a new AS project
- Create a new ts file and paste the following code

````
interface IFoo {
  doSomething: () => void;
}

export class Bar implements IFoo {
  doSomething(): void {
    
  }
}
````

**Expected result**
Build should pass without errors. The TS compiler recognizes the code as valid

**Actual result**
  ERROR TS2300: Duplicate identifier 'doSomething'.

**Comment by willemneal** [comment]
This is due to declaring `doSomething` as a property and then in the class you implement it as a method.  Changing the interface to declare a method [fixes it.](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKaW50ZXJmYWNlIElGb28gewogIGRvU29tZXRoaW5nKCk6IHZvaWQ7Cn0KCmV4cG9ydCBjbGFzcyBCYXIgaW1wbGVtZW50cyBJRm9vIHsKICBkb1NvbWV0aGluZygpOiB2b2lkIHsKICAgIAogIH0KfQojIWh0bWwKPHRleHRhcmVhIGlkPSJvdXRwdXQiIHN0eWxlPSJoZWlnaHQ6IDEwMCU7IHdpZHRoOiAxMDAlIiByZWFkb25seT48L3RleHRhcmVhPgo8c2NyaXB0Pgpsb2FkZXIuaW5zdGFudGlhdGUobW9kdWxlX3dhc20sIHsgLyogaW1wb3J0cyAqLyB9KQogIC50aGVuKCh7IGV4cG9ydHMgfSkgPT4gewogICAgY29uc3Qgb3V0cHV0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ291dHB1dCcpCiAgICBmb3IgKGxldCBpID0gMDsgaSA8PSAxMDsgKytpKSB7CiAgICAgIG91dHB1dC52YWx1ZSArPSBgZmliKCR7aX0pID0gJHtleHBvcnRzLmZpYihpKX1cbmAKICAgIH0KICB9KQo8L3NjcmlwdD4=)

You can also implement `doSomething` like `get doSomething(): () => void { return () => {} }`, but since AS currently lacks closures you wouldn't have access to `this`.

**Comment by MaxGraey** [comment]
Yes, that's a bug. Quick workaround is using `doSomething(): void;` instead `doSomething: () => void;`.

@dcodeIO will be great generalize function expressions and function declarations

**Comment by dcodeIO** [comment]
Not easy I fear, because one is a mutable field one can re-assign that is called indirectly while the other is an immutable method called directly. Perhaps with a `readonly` modifier, not sure.

**Comment by MaxGraey** [comment]
Wait is it possible reassign expression based method in AS?

**Comment by MKHenson** [comment]
Ah that makes sense! I was getting thrown off by the TS compiler not flagging anything, and yet the AS was flagging it.  Thanks guys. Really excited to see where AS goes :)
