### ISSUE TITLE
How to visit the "export" in AST at the entry file ?

### ISSUE THREAD

**Issue by xiong-pro** [AssemblyScript/assemblyscript#1899]
Hi, I use the `--transform` and `visitor-as` library to visit the AST node, and try to print it.

```ts
// entry file

export function apply(): void {
  // do something
}
```

```ts
// transform.ts

import {
  Parser,
  ExportStatement,
  ExportMember,
  ExportDefaultStatement,
  ExportImportStatement,
} from 'visitor-as/as';
import { TransformVisitor, utils } from 'visitor-as';

class WrapperTransform extends TransformVisitor {
  visitExportStatement(node: ExportStatement): ExportStatement {
    console.log('visitExportStatement --- ', node);
    return super.visitExportStatement(node);
  }

  visitExportMember(node: ExportMember): ExportMember {
    console.log('visitExportMember --- ', node);
    return super.visitExportMember(node);
  }

  visitExportDefaultStatement(node: ExportDefaultStatement): ExportDefaultStatement {
    console.log('visitExportDefaultStatement --- ', node);
    return super.visitExportDefaultStatement(node);
  }

  visitExportImportStatement(node: ExportImportStatement): ExportImportStatement {
    console.log('visitExportImportStatement --- ', node);
    return super.visitExportImportStatement(node);
  }

  afterParse(parser: Parser): void {
    const sources = parser.sources.filter(utils.not(utils.isLibrary));
    this.visit(sources);
  }
}

export = WrapperTransform;
```

But it does not print the `apply` function node that export in the entry file.

**Comment by willemneal** [comment]
This would be more appropriate for `visitor-as`, for future reference.  

The reason you can't find it is you are looking at export related statements.  For example, 
```ts
function apply(): void {}
export {apply};
```


You want to look for `FunctionDeclarationStatement`s.  Then you can check if the node is exported with `node.is(CommonFlags.EXPORT)`.  Otherwise you can hook in `afterInitialization` and the program object will have the exports.

Also you can use `utils.toString` to convert an AST node to a string.

**Comment by ApsarasX** [comment]
```ts
export function apply(): void {
  // do something
}
```
This code is a `FunctionDeclaration` with `CommonFlags.EXPORT` rather than an `ExportStatement`.

The relevant code is located at https://github.com/AssemblyScript/assemblyscript/blob/7ada77c3e603fcf7bfba1aa7228423aca9747497/src/parser.ts#L217-L219
https://github.com/AssemblyScript/assemblyscript/blob/7ada77c3e603fcf7bfba1aa7228423aca9747497/src/parser.ts#L280

**Comment by ApsarasX** [comment]
@xiong-pro 同学，我也是蚂蚁集团的，目前团队在做AssemblyScript编译器定制，可以加钉钉聊？
![1d78f28ff42e80504266aaf233d93e58](https://user-images.githubusercontent.com/24390069/121553996-5e15b580-ca44-11eb-85bc-55ad9745be09.jpg)

**Comment by ApsarasX** [comment]
@xiong-pro 同学，我也是蚂蚁集团的，可以加钉钉聊？

![1d78f28ff42e80504266aaf233d93e58](https://user-images.githubusercontent.com/24390069/121554280-9ae1ac80-ca44-11eb-86a7-c0d00fd8fde6.jpg)

**Comment by xiong-pro** [comment]
@willemneal Thanks for reply.
Is there any AST spec for AS (like the [babel's](https://github.com/babel/babel/blob/main/packages/babel-parser/ast/spec.md)), or documents ?
Now I'm so confused about which api I should use, while visiting the AS node, and don't know the tree's structs. 🧐

**Comment by willemneal** [comment]
Yeah a spec would be a good idea. For now the best way to learn it is to look at the [`ASTBuilder`](https://github.com/willemneal/visitor-as/blob/master/src/astBuilder.ts).

Looking at the babel spec, I think we should follow suit and move the AST Nodes to interfaces.
