### ISSUE TITLE
Sharing data in two Transforms

### ISSUE THREAD

**Issue by LittleMoi** [AssemblyScript/assemblyscript#1914]
@MaxGraey Hello~I am come back. I'm working on this thing, but there is some problem. I implement it by two Transform. **The question is written in the comment**

```typescript
class UniqueIdVisitor extends ClassDecorator {
    visitFieldDeclaration(node: FieldDeclaration): void {
        throw new Error("Method not implemented.");
    }
    visitMethodDeclaration(node: MethodDeclaration): void {
        throw new Error("Method not implemented.");
    }
    visitClassDeclaration(node: ClassDeclaration): void {
        this.log(node.name.text);
    }

    get name(): string {
        return "uniqueid";
    }
}
```

And 
```typescript
class UniqueIdOf extends TransformVisitor {
    visitCallExpression(node: CallExpression) {
        if (
            node.expression instanceof IdentifierExpression &&
            node.expression.text === "uniqueidof"
        ) {
            const n = node.typeArguments[0];
            if (n instanceof NamedTypeNode) {
                const genericType = n.name.identifier;
                // How can i get the data of family id from UniqueIdVisitor? Transform's Program or Parser?
                return Node.createIntegerLiteralExpression(i64_new(1), node.range)
            }
        }
        return super.visitCallExpression(node);
    }

    afterParse(_: Parser): void {
        this.program.OBJECTInstance
        let sources = _.sources.filter(utils.not(utils.isLibrary));
        this.visit(sources);
    }
}
```

_Originally posted by @LittleMoi in https://github.com/AssemblyScript/assemblyscript/issues/1360#issuecomment-863729122_

**Comment by LittleMoi** [comment]
I haven't received any answer till now.

**Comment by MaxGraey** [comment]
I don't think you can share data between two transforms. It seems you're using `visitor-as`. Pehaps @willemneal know more about this

**Comment by willemneal** [comment]
This is in the wrong repo, [visitor-as](https://github.com/willemneal/visitor-as) is the correct given your use of the visitor framework.  However, I'll answer here.

The issue is if you have two transformers they won't be aware of the other.  They are both independently imported by the compiler.  So you have two options:

1) Don't use the class decorator visitor.  Instead inherit `BaseVisitor` and use functions from the `utils` to test for decorator on a class declaration. While visiting keep found nodes in a collection.  Then in your second transformer use the first visitor to visit the sources.   Then you'll be able to access the data for your next visit pass.

**Comment by willemneal** [comment]
The other solution (though it will make typescript unhappy) is to inject data into the source object.  Though you'll need some `//@ts-ignore`'s over the lines that write and read that data.

**Comment by LittleMoi** [comment]
@willemneal Thanks for your reply. The solution "injected dataa into source object" is working well. Prefab I can fork the repo 'visitor-as', implements more base class to adapte to mine.
