### ISSUE TITLE
[Question] Nullability checks only work with triple equals

### ISSUE THREAD

**Issue by otaviopace** [AssemblyScript/assemblyscript#1988]
Maybe this is intentional, and that's the way the language should behave, but personally I would find very useful if the `== null` and `!variable` also triggered the [nullability check feature](https://www.assemblyscript.org/basics.html#nullability-checks). Example:

```typescript
export function universe_answer(): i32 {
  let bar: string | null = "bar";

  if (bar === null) { // nullability check works
  // if (bar == null) { // nullability check fails
  // if (!bar) { // nullability check fails
    return 50;
  }

  let foobar = "foo" + bar; // line that fails if nullability check isn't working

  return 42;
}
```

> Note: I know there are template strings in the language already, I just did it this way so the error is clearer for the example

Error:

```
ERROR TS2322: Type '~lib/string/String | null' is not assignable to type '~lib/string/String'.

   let foobar = "foo" + bar;
                        ~~~
 in assembly/index.ts(18,24)

/usr/local/lib/node_modules/asbuild/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

[1 compile error(s)]
```

![スクリーンショット 2021-07-16 0 12 09](https://user-images.githubusercontent.com/15306309/125885995-a1ee6fdf-0ffe-4c1c-98d5-777c4c3af3d2.png)

Are there any design reasoning in why this is this way? Just curious really 🙂

**Comment by dcodeIO** [comment]
This is mostly an implementation detail in that `==` can be overloaded, so it executes a function that we would have to evaluate fully in order to know, while `===` performs an identity comparison, which we can trivially evaluate. The underlying mechanism there is that we essentially run the condition in question through Binaryen, and look if it is true-ish or false-ish.

So far it seemed that the alternative there is to internalize the `==` operator, but then it becomes non-overloadable, or, if we want to retain the option, needs a new clever mechanism that nobody has found yet.

**Comment by trusktr** [comment]
AS still doesn't have full type narrowing and analysis of nullability flow. See discussion about that in https://github.com/AssemblyScript/assemblyscript/issues/1973.

To get around these issues, you can usually add a non-null assertion. For example, if you have something like

```ts
let something: Foo | null = null
// ...

let result: Foo = null
if (something) result = something // <----- Error!
```

you will get the error in AS, although TS will understand fine that `something` is not `null` at that point.

To solve that issue (for now, until type narrowing and null flow is improved) you can use `!` to tell AS you know something is not `null`:

```ts
let something: Foo | null = null
// ...

let result: Foo = null
if (something) result = something! // <----- ok
```
