### ISSUE TITLE
What's the meaning of nullTerminated parameter for String.UTF8.decode

### ISSUE THREAD

**Issue by victortanjh** [AssemblyScript/assemblyscript#2020]
When using String.UTF8.decode to change ArrayBuffer to String, is there any difference between setting nullTerminated=true or not?
If I do not set nullTerminated=true  and put any ArrayBuffer as  input parameter of String.UTF8.decode, is there a risk of "out of bound memory"?

Thank you very much.

**Comment by MaxGraey** [comment]
`nullTerminated` means decoder try calculate string's length by interpreting the end of the string as "\0" instead of counting the length based on the assumption that it is UTF8. This is useful for ASCII strings in languages such as C. Generally you can calculate the len of string in advance anyway, so this is just a small opportunity to optimize

**Comment by victortanjh** [comment]
Thank you. Thank you for your reply.
