### ISSUE TITLE
DataView around an ArrayView buffer is not writing to the same buffer

### ISSUE THREAD

**Issue by Dudeplayz** [AssemblyScript/assemblyscript#2183]
I have the following usage of an array.
Array creation (JS) -> Copy to WASM -> Store in object -> Create a DataView around the buffer -> Create an ArrayView (JS) for this array -> Create a DataView around the buffer (JS) -> Start accessing the arrays and data views on both sides.

The problem which occurs is, that it seems that the underlying buffer isn't the same. On the JS side, the DataView writes to some other (new) buffer. Am I doing something wrong? Is this case even supported?

Here is the WASM side:
```ts
readonly data: Uint8Array = new Uint8Array(0x1000);
readonly dataView: DataView = new DataView(this.data.buffer);

export function getData() : Uint8Array {
   return data;
}
```

JS side:
```ts
readonly data: Uint8Array;
readonly dataView: DataView;

constructor(private wasm: ResultObject & { exports: ASUtil & typeof MyModule }) {
    this.data = this.loader.__getUint8ArrayView(wasm.exports.getData());
    this.dataView = new DataView(this.data.buffer);
}

testDataView() {
    const compare = 0xFFFF
    this.dataView.setUint16(0, compare, true)
    const get = this.dataView.getUint16(0, true)
    const l = this.data[0];
    const h = this.data[1];
    console.table({compare: compare, get: get, low: l, high: h})
}
```

Results in:
```
┌─────────┬────────┐
│ (index) │ Values │
├─────────┼────────┤
│ compare │ 65535  │
│   get   │ 65535  │
│   low   │   0    │
│  high   │   0    │
└─────────┴────────┘
```

I haven't checked if the value is correctly set for the WASM side, but I expect that this is also not working.

**Comment by dcodeIO** [comment]
In the example above, it seems that `new DataView(this.data.buffer)` would create a view of the entire memory, which `this.data` is a slice of (region as of .byteOffset and .byteLength, but .buffer is still the entire memory). Could this be the problem?

**Comment by Dudeplayz** [comment]
You mean the buffer start is not 0 because it's a wider memory buffer? Then it seems this is the reason and I have to pass the start index from the ArrayView to the DataView. Is this correct?

**Comment by Dudeplayz** [comment]
Thanks @dcodeIO,
you were right. I was able to fix it by passing the byte offset to the DataView:
`this.dataView = new DataView(this.data.buffer, this.data.byteOffset, this.data.byteLength);`

I also passed the byteLength, is this necessary? The underlying array is fixed in size.

**Comment by dcodeIO** [comment]
Not sure if it makes a difference, say in perf, when the backing slice is larger than necessary, but it would make a difference when an access would otherwise be out of bounds. I'd specify it for correctness :)

Also note that there is one aspect to take care of in the Wasm JS API when working with views (instead of copies) on the memory: When memory grows on the Wasm end, say because the module requires additional memory, `buffer` will become "detached" and accessing any old views on the memory will throw. Even though this is not the case here as it seems, when it happens this can be surprising. In case it ever happens, a good workaround is to set `--initialMemory` to a large enough value, or trigger a large enough allocation that is immediately free'd before views are used.

**Comment by Dudeplayz** [comment]
Thanks for the hints! Can these errors occur only when the array grows or when any memory in the module grows? The project I am working on is mainly fixed in size (Avr simulator), but there could be some callbacks get registered at runtime. I will keep it in mind. The error you mentioned is clearly visible so that I can run until it occurs?
