### ISSUE TITLE
Support importing JSON files like TypeScript

### ISSUE THREAD

**Issue by leighmcculloch** [AssemblyScript/assemblyscript#2251]
With `assemblyscript@0.20.3`, importing a JSON file like this:
```ts
import f from "./f.json";
```
Or like this:
```ts
import f from "./f.json" assert { type: "json" };
```
Results in this error:
```
ERROR TS6054: File 'f.json.ts' not found.
```

Importing JSON files into AssemblyScript files does not appear to work, however this is supported in TypeScript 2.9+.

For continuing portability with TypeScript it would be ideal to support this. Importing JSON files are also a great way to import external data into applications at compile time, so it would make importing data into AssemblyScript applications easier too.

**Comment by leighmcculloch** [comment]
I also tried with including these options in tsconfig.json, to no avail:
```
"resolveJsonModule": true,
"esModuleInterop": true
```

**Comment by dcodeIO** [comment]
One interesting question here is, what static type should `f` have? Perhaps, adding basic JSON support first could help to inform this issue, hmm.

**Comment by leighmcculloch** [comment]
I would expect it to be an anonymous class/struct type with structure defined by its contents. Do we have any types that work like this already?

Adding runtime JSON support seems like a pretty different problem space and adding importing JSON doesn't require any runtime JSON.

**Comment by dcodeIO** [comment]
Perhaps, yeah. I still wonder, however, how we'd infer appropriate types since, for example, going with `number` (= `f64`) for all numeric values seems as if it will lead to some frustration, and there are no type annotations in JSON. Or perhaps it won't, but looks like something to think about. Could be worked around for now by importing a .ts file instead, then including the necessary type annotations.

**Comment by leighmcculloch** [comment]
I would lean towards the most predictable outcome. Given all `number`s in JSON are 64-bit floats, I think it makes sense to type them as `f64` in AssemblyScript. A valid JSON file will never store a 64-bit integer as a number, it'll probably be stored as a string. This means it works the same as it does in TypeScript, and increases portability.

An application can always cast the values to integer types, and since the import occurs at compile time, all the values within it are known at compile time, and any cast of those compile-time values can occur at compile time so the f64 value doesn't necessarily end up in the final wasm. 

Since 64-bit integers are often typed as strings in JSON, they'd need to be parsed. It'd be sad to have to do that parseInt call at runtime. It would be ideal if code that called `parseInt` with a string value known at compile-time from a JSON import could be parsed at compile-time. Or more likely, as I think you're hinting, maybe importing from JSON should require an additional `assert` parameter which is the type to parse into?

**Comment by trusktr** [comment]
I think someone should write a transform for this, even if it is shipped with AS npm package. 

Also have you tried as-json? https://github.com/JairusSW/as-json

**Comment by leighmcculloch** [comment]
According to the folks on discord as-dom is for runtime JSON deserialization/serialization, but this issue is about compile time JSON deserialization.

**Comment by trusktr** [comment]
Yeah, runtime would be useful. One question is how to make accurate types? Even with TS JSON type generation, the types are not ideal sometimes, so I end up writing my own better types. For example, TS cannot guess missing optional types. But in case of existing types it works pretty well for a use case like reading package.json.

In any case, at least as-json can get you something working right now. Maybe parts of it can be reused for the compile transform? @JairusSW

**Comment by JairusSW** [comment]
Yes, so lets say you have a `.json` file like this
`f.json`
```json
{
    "foo": "bar",
    "moo": 123
}
```
In order to implement `import f from "./f.json";`, we would do the following
1. Create a transform
2. Parse the .json file and keep the keys and values handy. Also, note the types
3. Create a class that contains the fields along with their assigned type
4. Create a variable called `f` and replace the `import f from "./f.json";` line with it
5. Assign that as type `(class-name)` and plug in the data values to the data struct

We could use an alternative type instead of using primitive and string types.
Thinking of something akin to [jsonType.ts](https://github.com/JairusSW/as-json/blob/rewrite/assembly/jsonType.ts)
@DogWhich may be able to shine some light on this
