### ISSUE TITLE
storing and loading types from heap in a portable way

### ISSUE THREAD

**Issue by Born2Go** [AssemblyScript/assemblyscript#226]
to develop some things I run my assemblyscript via node using the portable std
the problem I faced now it that the portable implementation of load and store builtins dont diferenciate between types 

the current implementation always load and stores a byte (as in typescript it is the same function with generics)

> globalScope["store"] = globalScope["__store"] || function store(ptr, value, offset) {
>   HEAP[ptr + (offset | 0)] = value;
> };
> globalScope["load"] = globalScope["__load"] || function load(ptr, offset) {
>   return HEAP[ptr + (offset | 0)];
> };

can we have diferent methods to load/store diferent types?
like: load_u8 / load_u32 ?
or the signature of load/store be like "ptr, size, offset"?
this way it will be possible to implement the portable version of those functions

**Comment by dcodeIO** [comment]
The plan here is to also provide `i32.load`, `f32.load` etc. eventually, but that's not implemented yet. The [implementation of portable memory](https://github.com/AssemblyScript/assemblyscript/blob/master/std/portable/index.js#L221-L249) is relatively basic at this point.

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) because it has been lingering for quite a while and it seems unlikely to have a clear way forward (the portable memory implementation has been removed meanwhile). From my experiments so far, the memory models in Wasm and JS are just too different to make this work in a straight-forward way that'd be any better than a hack.
