### ISSUE TITLE
Unexpected DCE optimization when building a seperate wasm file include all libs and specific runtime

### ISSUE THREAD

**Issue by ApsarasX** [AssemblyScript/assemblyscript#2270]
I want to build a seperate wasm file include all libs and specific runtime.

So I comment the following code in `cli/index.ts`

https://github.com/AssemblyScript/assemblyscript/blob/d884ac8032b2bfa0caf26d4dc11d99c5a9543c13/cli/index.js#L792-L846

Then I build the whole assemblyscript by `npm run build`.

Finally I execute `node bin/asc.js assembly/index.ts` (`assembly/index.ts` is empty file)

But the emitted wasm file just like the below:

```wat
(module
 (global $~lib/memory/__data_end i32 (i32.const 8))
 (global $~lib/memory/__stack_pointer (mut i32) (i32.const 16392))
 (global $~lib/memory/__heap_base i32 (i32.const 16392))
 (memory $0 0)
 (table $0 1 1 funcref)
 (elem $0 (i32.const 1))
 (export "memory" (memory $0))
)
```

All libs and runtime are still deleted by DCE optimization.

How to ensure that the stdlib and runtime are not deleted?

**Comment by dcodeIO** [comment]
With optimizations disabled, this rather looks like tree-shaking, i.e. nothing is compiled because nothing is exported. Specifying `--exportRuntime` should make sure that the runtime is present, while other parts of stdlib are trickier. For instance, there is no code for an `Array<T>` as long as there is no known concrete `T`. I fear that right now this is non-trivial.

**Comment by ApsarasX** [comment]
Thank you for your answer
