### ISSUE TITLE
Missing function with raw bindings

### ISSUE THREAD

**Issue by jonathannorris** [AssemblyScript/assemblyscript#2516]
Hey AS team,

Seems like the compiler isn't exporting functions that do not have and input parameters when run in `--bindings raw` mode.

For example we have a simple function without any input parameters:
<img width="439" alt="image" src="https://user-images.githubusercontent.com/1219069/191066825-e76ff3a0-0d6e-4891-8a3a-adfa4aafc446.png">

It shows up in the `.wat` and `.map` files: 
<img width="588" alt="image" src="https://user-images.githubusercontent.com/1219069/191066978-2c67de21-d0a3-4ef1-8370-ab5f0c763a66.png">

Also in the `.ts` type description: 
<img width="385" alt="image" src="https://user-images.githubusercontent.com/1219069/191067145-5a288c8e-b6d3-4b26-8aa4-2522fc4fe1dc.png">

but doesn't show up in the generated `.js` bindings.

**Comment by dcodeIO** [comment]
Functions without a need for glue code come directly from the .wasm file, while functions that need glue code are present in the .js file, wrapping their respective .wasm functions. Unless this is buggy, the final exports object should show all of them.

**Comment by raddad772** [comment]
I am in the same boat. I cannot figure out how to get access to a function that requires no glue code. I'm just about to throw my hands up and make it require some so that I can get to it. how do I import the function "straight from the wasm?"

Specifically, I have this function

```
export function gp_get_input_buffer(player: global_player_t): usize {
    return player.input_buffer;
}
```

I do

```
this.wasm = await instantiate(await WebAssembly.compileStreaming(this.wasm_fetch), {})
```


and later

```
this.input_buffer_ptr = this.wasm.gp_get_input_buffer(this.global_player);
```

but get error, cannot read properties of 'undefined' (reading gp_get_input_buffer).

**Comment by dcodeIO** [comment]
Perhaps to clarify: Unless there is a deeper issue, which I don't see any indications for, the function in question in fact exists, but only in the `.wasm`, not in the accompanying `.js` file. It does not show up in the `.js` file because it is so simple that it does not require wrapping of arguments or similar, and is instead immediately re-exported from the `.wasm` file. The `.d.ts` describes the combination of both files.
