### ISSUE TITLE
more useful assert in ast.ts when unknown NodeKind

### ISSUE THREAD

**Issue by mariusa** [AssemblyScript/assemblyscript#2566]
https://github.com/AssemblyScript/assemblyscript/blob/688dcd23eaebaa8d82185b11ec5181c010726714/src/extra/ast.ts#L367

How about adding 
```
console.error(`Unknown node kind ${node.kind}`)
```
before assert(false) ? It would add some more information and be useful when debugging compiler errors.

**Comment by mariusa** [comment]
not stale

**Comment by dcodeIO** [comment]
The `assert`s in the compiler are expected to never be hit. If one is hit nonetheless, there's not much benefit in printing a message, since to fix the problem, one would want to look at file and line number of the assertion anyway and then go and figure out what's wrong in more detail. So, while a message *can* be attached like `assert(false, "Unexpected kind")`, that's typically not done since the message would just clobber static memory.

**Comment by mariusa** [comment]
Ok, thanks. Reason for request: got an assert and took me almost 1hr to find the cause. Maybe 16 bytes of memory can be spent here and there (for compiling, not at runtime) until 1.0 is shipped most of these issues will be solved.

**Comment by dcodeIO** [comment]
Ultimately, messages should then be added to all asserts, which, given the number of asserts, amounts to a lot of messages. All of them would then be present, with no distinction between compiling and runtime. I can ofc relate to the desire to have some message, so this is a bit more human friendly, but when thinking this through there is really only a psychological effect. If one can fix the issue, one doesn't need the message. If one can't, the message will end up in an issue, but those then fixing the problem don't need it.
