### ISSUE TITLE
Can't use {} to create an instance when the constructor of call has any arguments.

### ISSUE THREAD

**Issue by LiaoPeng** [AssemblyScript/assemblyscript#258]
The code [https://webassembly.studio/?f=l4cxr3q2wva](https://webassembly.studio/?f=l4cxr3q2wva)

Get errors:
```shell 
ERROR AS216: Constructor of class 'Car' must not require any arguments.
```
Expected:
Compiled successfully.

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) because it is outdated, in that classes instantiated from object literals have meanwhile even been limited to classes without a constructor to avoid issues with constructor logic that turned up in attempts since then. I expect this to be attempted again in the future, but at this point it's not a high priority.
