### ISSUE TITLE
Expose Wasm global.get function

### ISSUE THREAD

**Issue by xtuc** [AssemblyScript/assemblyscript#2640]
### Feature suggestion

I'm manually linking Wasm code generated by AssemblyScript in a hand crafted Wasm module. In my AssemblyScript code I'm trying to access Wasm globals (that I added manually to the module) but AssemblyScript doesn't seem able to read globals directly.

My feature request is: add `global.get` in AssemblyScript that translates to the corresponding Wasm instruction. 

Thanks!

**Comment by dcodeIO** [comment]
Regarding a `global.get` builtin: Under the hood, AS calls a Binaryen API to emit a `global.get` instruction: [`BinaryenGlobalGet`](https://github.com/WebAssembly/binaryen/blob/90c726a606cf8f99307a41d8f889de4e1221c4f8/src/binaryen-c.h#L799-L801). Instead of an index, this API takes a name, as is one of [Binaryen's design principles](https://github.com/WebAssembly/binaryen#design-principles). However, if there is no mapping from name to index, as would be established by the [presence](https://github.com/WebAssembly/binaryen/blob/90c726a606cf8f99307a41d8f889de4e1221c4f8/src/binaryen-c.h#L2804-L2808) of a global, a raw `global.get` instruction cannot be emitted, since in the binary the name first needs to be translated to the index, whereas the name only goes into the debug section.

An alternative to achieve a similar effect is to declare an imported global instead, and access it normally. Then, during linking, the import is satisfied with a global that exists elsewhere, and accesses hence replaced.

```ts
@external("module", "name")
declare const myGlobal: i32; // or 'let' if mutable

myGlobal; // -> global.get $myGlobal
```

Would such an approach work for your use case? Not sure if changes to Binaryen are practical in this regard.

**Comment by xtuc** [comment]
Interesting, thanks for the explanation. 

In my use case that might work, I'm accessing globals with an arbitrary index. If TypeScript allows me something like this `globalThis["myglobal" + I]`. That should work but the ideal would be to be able to emit the wasm global.get instructions.
