### ISSUE TITLE
Communication with emscripten c++ module? Can AssemblyScript be used as side module?

### ISSUE THREAD

**Issue by alienself** [AssemblyScript/assemblyscript#2641]
### Question

Hi,

I would like to know if it is possible to compile AssemblyScript as a dynamic library or side module that can be used with an Emscripten C++ module and possibly sharing the same memory?

Any idea if this is possible?

**Comment by dcodeIO** [comment]
There is currently no support for dynamic linking, unfortunately, and little is known about what the future holds. Perhaps @kripken has an idea (seeing [his response](https://github.com/emscripten-core/emscripten/discussions/18670#discussioncomment-4885128) on the Emscripten end of the issue) on how to approach this ideally (could Binaryen help?).

Last time I thought about this there was the idea to *at least* make it so that AS can emit relocatable modules, but given that this approach wouldn't solve all the challenges (i.e. two competing memory managers wanting to grow their own heaps, one with a bundled GC) and future options like multiple memories or Wasm GC, nothing usable materialized just yet.

**Comment by alienself** [comment]
Thank you for your reply and for this detailed explanation, it makes sense. Do you think that this could eventually be supported or is this highly unlikely? 

My use case would be to write the core of my app in C++ and have a scripting capability that allows user to write in AssemblyScript and access exposed C++ classes from the core app module. 
I don't want to use JS directly for the scripting part because the JS memory would not be shared and the interop overhead too high. 

Perhaps AssemblyScript is not the right fit for this? Are you aware of any other project that would play well with wasm/emscripten?
