### ISSUE TITLE
Efficient Asset Inlining

### ISSUE THREAD

**Issue by kefniark** [AssemblyScript/assemblyscript#2675]
### Question

Hi there,

Small question relative to AssemblyScript data inlining.
I'm working on some small 2d game in assembly script, and I'm trying to inline some data into the wasm (a spritesheet).
So I wrote a small script which convert the original 512x512 `.png` file into an array buffer

```ts
// Color palette: 256 x u32 (RGBA)
const colorPalette = new Uint32Array(1024);
colorPalette.set([
  0x140c1cff, 0x442434ff, 0x854c30ff, 0xd04648ff, 0x597dceff, 0x8595a1ff, 0xd2aa99ff, 0xdad45eff, 0x0, 0x6dc2caff, 0x4e4a4eff, 
  // ...
], 0);

// Spritesheet: 512 x 512 u8 (pixel with indexed color)
const data = new Uint8Array(262144);
data.set([
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
  // ...
]);
```

It works fine, It build and I can access and use that spritesheet at runtime👍

My problem, the `release.wasm` size jump from **15KB to 950KB** after doing that. It looks like this way of inlining data is really inefficient storage wise. I tried different thing but didn't find an easy and efficient way to embed a data buffer into wasm code directly, as a chunk of memory to preload.
The more efficient solution I found so far, is to write the same data buffer into a separated binary file, then load it at runtime from JS side and copy it into from the host to wasm memory. When I do that, the file size is only **258KB** (3~4x times smaller).

And If we measure after gzip, the difference get smaller but still noticeable.
```
Without compression:
* DataBuffer in wasm: ~940KB
* DataBuffer in a separated binary file: ~250KB (-74%)

With gzip:
* DataBuffer in wasm + gzip: ~25KB
* DataBuffer in a separated file + gzip: ~17KB (-32%)
```

Does anyone know if there an efficient way to serialize binary data efficiently in the `.wasm` file? (image, font, dataset, ...)

**Comment by dcodeIO** [comment]
The cheapest way to embed arbitrary data is to make use of `memory.data`, placing a sequence of values into static memory and returning the offset:

```ts
const colorPalette = memory.data<u32>([ ... ]);
```

To load a specific value: `load<u32>(colorPalette + i * sizeof<u32>())` for the `i`th element

If a managed array-like object living in the heap is preferred, `StaticArray` can be used instead:

```ts
const colorPalette: StaticArray<u32> = [ ... ];
```

Here, to obtain a specific value: `colorPalette[i]`

The same also works with `Array`, but it will involve one level of indirection as it wraps a buffer. Typed arrays are currently not similarly supported, but `StaticArray` should be a better choice most of the time anyway due to avoiding the indirection.

**Comment by kefniark** [comment]
Thanks, wow indeed `memory.data` is the way to go 👍
