### ISSUE TITLE
Inconsistent use of __retain in generated bindings?

### ISSUE THREAD

**Issue by donmccurdy** [AssemblyScript/assemblyscript#2699]
### Bug description

When generating bindings for a function that accepts multiple `StaticArray<f32>` arguments, I've noticed that the bindings call `__retain` for some but not all of those arguments. I'm using the  arguments the same way in the code, and based on my reading of the bindings, probably both pointers should be retained.

That said — I'm pretty new to AssemblyScript, apologies if I've misunderstood the memory lifecycle!

### Steps to reproduce

1. Build the export below.

```typescript
export function dot(a: StaticArray<f32>, b: StaticArray<f32>): f32 {
	let result: f32 = 0;
	for (let i = 0; i < a.length; i++) {
		result += a[i] * b[i];
	}
	return result;
}
```

2. Observe the generated bindings.

```js
  dot(a, b) {
      // assembly/test/dot(~lib/staticarray/StaticArray<f32>, ~lib/staticarray/StaticArray<f32>) => f32
      a = __retain(__lowerStaticArray(__setF32, 4, 2, a, Float32Array) || __notnull());
      b = __lowerStaticArray(__setF32, 4, 2, b, Float32Array) || __notnull();
      try {
        return exports.dot(a, b);
      } finally {
        __release(a);
      }
    }
```

3. Should `b` be retained and released, as well?

### AssemblyScript version

v0.27.3

**Comment by dcodeIO** [comment]
It is not necessary to retain `b` because when calling `dot`, the arguments are retained by means of putting these onto the shadow stack. But `a` must be retained (ensured to be pinned) since it is not yet on the shadow stack and making `b` involves an allocation, which can step the GC.

**Comment by MaxGraey** [comment]
I guess necessary to document this somehow in docs / FAQ

**Comment by dcodeIO** [comment]
Looking at the linked issue, it seems that the project is using the minimal runtime. In this case there is no shadow stack, but since `__collect` is to be invoked manually, this is not a problem as long as one keeps in mind that, with the minimal runtime, `__collect` must not be invoked when the execution stack is not empty, i.e. not somehow directly or indirectly by `dot`.

**Comment by donmccurdy** [comment]
At least for the moment, I'm also using [custom bindings](https://github.com/donmccurdy/keyframe-resample-wasm/blob/480911d7c12ced870e37b599e9dc8d64200731a4/src/bindings.ts#L107-L120) with the minimal runtime. I'm not sure I understand the implications of the shadow stack, but presumably calling `__retain` for both arguments is also OK in my own bindings? I do only need to invoke `__collect` manually, at the end of each WASM call.

**Comment by dcodeIO** [comment]
Yes, it is OK to call `__retain` for the second argument as well, though it is not necessary. In fact, since the minimal runtime is used, which does not automatically step the GC, it is technically not necessary to call `__retain` at all *unless* an object is exclusively referenced from the JS side of things for longer than the next `__collect` call.
