### ISSUE TITLE
This project is dead? The last commit was 28 april?

### ISSUE THREAD

**Issue by sirlordt** [AssemblyScript/assemblyscript#2715]
### Question

Lot of stuff is happening in webassembly tech but this repo not had any commit in months.

This project is dead?

**Comment by dcodeIO** [comment]
As for me, I'm currently taking a break, since a) Wasm in the browser was essentially dead (I hope it'll recover with GC an such) and b) I couldn't take the constant attacks from the general direction of the Bytecode Alliance against this project and particularly myself anymore (I hope I'll recover). Some background [here](https://www.assemblyscript.org/standards-objections.html). That said, I'm not gone, still actively watching.

**Comment by CountBleck** [comment]
[Discord](https://discord.gg/assemblyscript)'s probably a better place to talk about this, if you have it.

**Comment by abflow** [comment]
I wished we had an AssemblyScript version of binaryen, so that we could compile the whole workflow as a wasm for use within the browser.
