### ISSUE TITLE
Typescript AssemblyScript Transpiler

### ISSUE THREAD

**Issue by tysonrm** [AssemblyScript/assemblyscript#2741]
### Feature suggestion

The title says it all. Transpile TS to AS.

**Comment by CountBleck** [comment]
It's not so simple.

TS is a much broader language than AS. `any` is one example of a feature that wouldn't quite work in AS. On a sidenote, AS also has some features that don't map to TS either. Still, AS strives to be easy to use for TS users.

Therefore, the TS features that AS can reasonably support (without boxing and such) should actually be implemented in AS and not transpiled. That way, AS doesn't have the overhead of supporting overly dynamic parts of JS, and the user is pointed towards more performance-friendly alternatives. By overly dynamic, I mean parts of JS that, implemented in AS, would greatly diminish the performance gained from using a Wasm-based language.

With that in mind, what features of TS are you looking for?

**Comment by tysonrm** [comment]
So the transpiler would take into account what you mention and either rewrite it or throw an exception. Types would be infered to the extent possible. Common data structures would be transpiled to account for memory allocation. One comment on the above, TS does to some extent limit the dynamic nature of JS with the type system.  Like you imply, the transpiler wouldn't magically account for all the ways in which a TS module could'nt be compiled to wasm, but it would handle common used objects, like Map for instance.

**Comment by CountBleck** [comment]
> To address the any type, the transpiler would require type inference.

That genuinely sounds like a bad idea. `any` as a return type could mean a function could return literally any type (number, object, etc.). Type inference (if I understand you correctly) sounds error-prone: let's say a function has a return type of `object`. In one caller, surrounding code might allow a smart:tm: compiler to deduce the object has fields `a`, `b`, and `c`. Still, that does not by itself reveal the types of those fields. Also, it relies on assuming the code to be typesafe. Moreover, if we base this inference on the code within the callee, the resulting return type could be some union (from branches), and fields may be set from parameters (which could also be `any`). This idea would lead to jank and slowness.

> As for the other non-mapping features, im not sure how to address other than case by case.

I'll talk about one such case in the very last part of this reply.

> Obviously, we would want the transpiler to account for memory allocation. Otherwise, its just a linter.

I don't follow. In an earlier edit, you also mentioned Maps. AS has a built-in memory allocator and GC (both are included when your code requires them), as well as an implementation of Map.

> There will be functions that require WASI. I assume this can be handled.

Automatically using WASI functions is not a priority for AS. `@assemblyscript/wasi-shim` replaces relevant standard library functions with versions that call WASI functions, and third-party libraries (IIRC, it was `as-wasi`) should provide features like FS access. I can sort-of see a use-case for Node.js hosts, where `@external("fs", "readFileSync")` would be used...

> Non-performant code patterns could be identified and rewritten or at least produce a warning.

An AS-specific pattern would be, for instance, using Array/TypedArray for an array with a fixed length at runtime instead of StaticArray. That isn't easy to detect (the length could be changed outside of the code that created the array). A JS/TS-specific, not-so-transpilable pattern would be dynamic property access (`foo[bar] = baz`). That can't be transpiled either, without generating unacceptably inefficient code. A tool that generates Wasm from TS while greatly sacrificing performance and code size for compatibility is not what AS aims to be, from my understanding.

**Comment by tysonrm** [comment]
Then perhaps a linter is the best we could do. Or some AI assisted code walkthrough trained on porting examples. That's really reaching, I know. What would be helpful is to generate an estimate of how much work it would be to port a given code base. Thanks for your careful analysis.
