### ISSUE TITLE
[Proposal] Inline javascript / typescript

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [AssemblyScript/assemblyscript#282]
It would be nice to have an possibility to place inline javascript/typescript code, that would be actually compiled to separate javascript file. This would allow to have for anyone its "glue code" placed directly in sources and have in glue code only that what is really used.

Example:

```typescript
import function log(txt: string): void {
  console.log(txt);
}

import function error(txt: string): void {
  console.err(txt);
}

function main(void): void {
  log('Hello world');
}
```

would be translated to javasctipt file

```javascript
const __getTextFromAssemblyScript = (addressOfText) => {
  //... implementation
}

const imports = {
  env: {
    log: (txt) => {
      txt = __getTextFromAssemblyScript(txt);
      console.log(txt);
    }
    //no "error" function here since it is not used
  }
};
```

**Comment by dcodeIO** [comment]
One issue I see with this approach is that the AS code relies on relative specific [type definitions](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/index.d.ts) and [compiler options](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly.json) that might make it hard to just inline some JS into it. I think ideally there'd be at least different files that can utilize distinct definitions according to their targeted environment.

I agree though that interoperability should be improved eventually. This might one day be solved by adding the ability to import from arbitrary JS modules, for example, or by some sort of glue generator that can otherwise help with generating the necessary bindings.

The way it works currently is to generate a d.ts for the WebAssembly module that then can be used for proper type checking on the TS side, plus `declare`ing the imports on the AS side.

**Comment by DanielMazurkiewicz** [comment]
> One issue I see with this approach is that the AS code relies on relative specific type definitions 

Hmmm...  What kind of issue with type definitions do you see?

There is already interfacing for imported from JS functions and it shouldn't require much more than that. The only issue I see is with passing i64 and u64, which is not possible and should produce a compilation error in such a case... 

The functionality can be also limited to basic types (strings, numerics, numeric typed arrays) and in my opinion that should be more than enough to do any kind of the "glue code" inside of assemblyscript.

> The way it works currently is to generate a d.ts for the WebAssembly module that then can be used for proper type checking on the TS side, plus declaring the imports on the AS side.

As for the compiler options, don't know much about that yet, but having an option of dead code removal, that could also affect inline javascript is something that would produce very nice tight code in opposition to using modules as you've described, not mentioning all those opportunities for quick adaptation of assemblyscript as first and main language for projects due to all king of future libraries with glue code for node.js/browsers.

**Comment by dcodeIO** [comment]
> Hmmm... What kind of issue with type definitions do you see?

The most prominent one is that AS uses the **noLib** option, implementing the standard library as its own runtime. Hence, any JS code would be limited to the exact set of features AS supports, and will display intellisense errors otherwise.

A while ago there has been the idea to do it the other way around, that is embedding AS in TS code, maybe using a custom transform attached to tsc to separate both, then generating both JS with tsc and a WASM with asc alongside each other. There'll be other issues, of course, but it at least hosts all the code in an environment that has all the features, leaving it to the programmer to take care to use supported constructs in `@wasm` annotated code only. Somewhat depends on how deep we can integrate with tsc, of course.

**Comment by MaxGraey** [comment]
Close due to inactivity. You free to reopen
