### ISSUE TITLE
Loop and variable bug

### ISSUE THREAD

**Issue by lortonx** [AssemblyScript/assemblyscript#2825]
### Bug description

The compiler considers "i" to be one variable, not two, and an infinite loop occurs.

### Steps to reproduce

   run
   
        for(let i = 0; i < 30; i++) {
            let i = 10
            while(i--) {}
        }

### AssemblyScript version

0.27.15

**Comment by CountBleck** [comment]
Actually, a separate local variable *is* created, but it shadows the first one. See [here](https://www.assemblyscript.org/editor#IyFvcHRpbWl6ZT1ub25lJnJ1bnRpbWU9aW5jcmVtZW50YWwKZm9yKGxldCBpID0gMDsgaSA8IDMwOyBpKyspIHsKICAgICAgICBsZXQgaSA9IDEwCiAgICAgICAgd2hpbGUoaS0tKSB7fQogICAgfQojIWh0bWwK). Lines 36-39 would be the `i++`, which is writing to local 1 instead of local 0.
