### ISSUE TITLE
How much memory?

### ISSUE THREAD

**Issue by 19Nazar** [AssemblyScript/assemblyscript#2845]
### Question

Good afternoon, I have a question. I have a custom environment in webassemble that will provide such functions. 
https://github.com/19Nazar/WasmZig
How much minimum memory will be required to run the assembly in python?

**Comment by CountBleck** [comment]
I'm confused. Is this a question pertaining to **AssemblyScript**, and not just WebAssembly?

**Comment by HerrCai0907** [comment]
> I'm confused. Is this a question pertaining to **AssemblyScript**, and not just WebAssembly?

Agree. The question is a little bit off-topic.

Back to the question, if "minimum memory will be required to run the assembly in python" means memory usage of wasm instead of the whole python program's memory. A good idea is to take a look memory section in *.wat file. And you can find the count of memory page (64k per page).
```
(memory $0 1)
```
Besides, `memory.grow` will increase the count of memory page during wasm running.

**Comment by 19Nazar** [comment]
My mistake, in AssemblyScript.
