### ISSUE TITLE
Support the proposal JS String Builtins?

### ISSUE THREAD

**Issue by sv158** [AssemblyScript/assemblyscript#2878]
### Question

Recently Chrome v130 add the support of js-string-builtins proposal. Are there any plans for AssemblyScript to support this phase-4 proposal?

https://github.com/WebAssembly/js-string-builtins/blob/main/proposals/js-string-builtins/Overview.md

**Comment by HerrCai0907** [comment]
Thanks for your suggestions.
But I would say there are not enough resource even for released WASM 2.0 features. So I cannot give you a clear plan about the new feature supporting.

**Comment by CountBleck** [comment]
Most likely not at this stage, since it would, in our case, only be useful for copying strings between Wasm and JS .

The stringref proposal would be much, much nicer, but it's practically stalled. Fully and properly implementing this proposal within AS (which would require implementing Wasm GC first) would mean the compiler would have to compile strings one way for the web (externrefs) and another for everywhere else (a u16 array), and this is less than ideal.
