### ISSUE TITLE
Convert Uint8Array to UTF-8 string in AssemblyScript module.

### ISSUE THREAD

**Issue by iwasaki-kenta** [AssemblyScript/assemblyscript#291]
Hello,

Given these imports:

```ts
@external("env", "_tag_len")
declare function tagLength(): i32

@external("env", "_tag")
declare function loadTag(offset: usize): i32
```

I would like to read a string of `tagLength()` size into a Uint8Array and thereafter convert it into a UTF-8 string.

How I'm trying to read into the Uint8Array and convert it into a UTF-8 string right now:

```ts
let tag: string = changetype<string>(new Uint8Array(tagLength()));
loadTag(changetype<usize>(tag));
```

Through the WebAssembly virtual machine I'm using to run the module, I tried print out `tag.length` however and got a large value `1634038371` which implies that the string did not get read properly.

Does anyone have any ideas?

**Comment by dcodeIO** [comment]
The inverse operation, that is encoding a string to an utf8 buffer, is already supported (`String#toUTF8`), while the inverse unfortunately isn't yet.

Also note that using `changetype` this way won't work - that really just changes the type of something if you know exactly what you are doing, but doesn't work to convert an `Uint8Array` to a `string` because these are represented differently in memory.

What would help here is implementing a `String.fromUTF8` helper that takes an offset in memory and possibly a byte length, and creates an UTF16 encoded proper `String` from it. You'd then copy the utf8 bytes into memory on the JS-side and call that function with the necessary parameters on the AS-side to decode them to a string.

Without that, what you can do currently is to convert the bytes to a string on the JS-side using an [utf8-library](https://github.com/dcodeIO/protobuf.js/tree/master/lib/utf8) first, and then use what the [loader](https://github.com/AssemblyScript/assemblyscript/tree/master/lib/loader) provides (here: `newString`) to create a string in memory.

**Comment by iwasaki-kenta** [comment]
What would be the ideal way to allocate a raw `u8` array of a given size, and to grab a pointer of it in that case?

I ported over a `readUTF8` helper function to read into a JavaScript string from a UTF-8 string.

```ts
function readUTF8(array: usize, len: i32): string {
    let i = 0, out = "";

    while (i < len) {
        let c = load<u8>(array + (i++));

        switch (c >> 4) {
            case 0:
            case 1:
            case 2:
            case 3:
            case 4:
            case 5:
            case 6:
            case 7:
                out += String.fromCharCode(c);
                break;
            case 12:
            case 13:
                let c2 = load<u8>(array + (i++));
                out += String.fromCharCode(((c & 0x1F) << 6) | (c2 & 0x3F));
                break;
            case 14:
                let cc2 = load<u8>(array + (i++));
                let cc3 = load<u8>(array + (i++));
                out += String.fromCharCode(((c & 0x0F) << 12)
                    | ((cc2 & 0x3F) << 6) | ((cc3 & 0x3F) << 0));
                break;
        }
    }

    return out;
}
```

**Comment by dcodeIO** [comment]
The ideal way to allocate an Uint8Array is to use the loader's `newArray` functionality:

```js
var arr = new Uint8Array([...]);
var ptr = myModule.newArray(arr);
myModule.doSomething(ptr);
```

With the new helpers in place, `doSomething` could look like this:

```ts
export function doSomething(arr: Uint8Array): void {
  var str = String.fromUTF8(arr.buffer.data, arr.length);
  ...
}
```
