### ISSUE TITLE
Limited type inference

### ISSUE THREAD

**Issue by t57ser** [AssemblyScript/assemblyscript#298]
This is a question/feature request.
Currently in order to compile, all functions must have their return value defined, even if it could be inferred. I was wondering why that is the case?
Let's take this simple example:
```javascript
export function test() {
	let x: i32 = 1;
	return x;
}
```
Here the compiler will tell me that a type is expected. Why can it not infer the type?
My first assumption was that since i32 is just a type assigned to number, that typescript will tell asc that the return type is of type number which is not sufficient information. But also for string or void we get the same behavior, which are valid types in AS.

**Comment by dcodeIO** [comment]
The most prominent reason is something like this:

```ts
function test(a: bool) {
  if (a) return 2;
  return 4.0;
}
```

In this example, there's no contextual type when compiling a `return` statement, hence making it rely on automatic type inferrence exclusively. The first return value will become `i32.const(2)`. The second becomes an `f64.const(4.0)`. Now, the first must either be recompiled, which requires restoring the original compiler state at that exact time, so it becomes a proper `f64.const(2)`, or wrapped within a conversion from i32 to f64. I'd rather avoid the latter because such a conversion is unnecessary, and the former because of the complexity it involves.

Another thing I'm worried about is that if a longish function always returns an integer literal, but somewhere in the middle also returns a float literal, that if one misses that single one there is no way to tell from a quick glimpse what the return value will actually be f64, not i32, potentially leading to issues down the road where vars are inferred to f64 again, even though expected to be i32.

**Comment by t57ser** [comment]
In the example you gave, typescript would infer the possible return values to be `2 | 4`
I think this is a valid case to require a return type, but when it is possible for typescript to nail it down to a specific type, then it should not be required. Although setting the return type is not much of a hassle, language features should be kept where possible for consistency.
Even if number types are completely disregarded, there would be a ton of valid use cases:
void, null, strings, classes
For example:
```
class My {
	public x: i32;
	public y: i32;
	constructor() {}
}

function test() {
	return <My> { x: 1, y: 2};
}
```
Typescript knows that the return type here is of type `My`.

**Comment by t57ser** [comment]
Thanks for the clarification.

**Comment by MaxGraey** [comment]
Closing this because it relate to language design and type safe conventions
