### ISSUE TITLE
Support inline object types

### ISSUE THREAD

**Issue by singpolyma-shopify** [AssemblyScript/assemblyscript#338]
```
export function add(a: { x: i32 }): i32 {
    return a.x;
}
```

**Comment by dcodeIO** [comment]
Should be doable, but with caveats. For example, a type `{ x: i32, y: i32 }` would be incompatible to `{ y: i32, x: i32 }` due to the fact that static field layout differs. Similarly, `{ x: i32 }` would be incompatible to `{ y: i32, x: i32 }` etc.

Question is, should it still be supported nonetheless? Currently, one has to use an explicit class to make it work, i.e.

```ts
class MyType { x: i32 }

export function add(a: MyType): i32 {
    return a.x;
}
```

**Comment by trusktr** [comment]
I think it can work, the ordering issues can be abstracted away. If the overall shape of objects is known, regardless of order, then could the compiler just ensure the same order in the output? Or can the compiler just pass the dereferenced values individually to the function parameters ?

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) as it appears to be outdated and superseded by efforts to use a class type instead, and create instances from object literals. The new approach has several advantages in that no virtual lookups are involved.
