### ISSUE TITLE
Unchecked assignment with index increment operator causes unreachable

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#391]
I seem to have found a bug that causes unchecked sets to access out of bounds.

```ts
class Serializer {
  public data: Float64Array = new Float64Array(1000);
  public index: i32 = 0;

  public write_two(inst: f64, a: f64, b: f64): void {
    unchecked(this.data[this.index++] = inst);
    this.data[this.index++] = a;
    this.data[this.index++] = b;
  }
}
```

Calling `write_two` throws unreachable in code with no optimizations, and actually causes runtime errors with optimized code.

~~I have reproduced the error here in webassembly.studio, [here](https://webassembly.studio/?f=exa600lbobi).~~

**Comment by MaxGraey** [comment]
You forgot add `import "allocator/arena";`:
https://webassembly.studio/?f=r3z5b8wgc7

**Comment by jtenner** [comment]
@MaxGraey this is correct. I keep forgetting the allocator. I can't seem to replicate the issue in wasm studio any more.

However I can definitely replicate it from the `canvas-as` repo I have on a fork.

Here's the error:

![image](https://user-images.githubusercontent.com/3761339/50524824-f6eb2d00-0aa5-11e9-8999-f2760040168e.png)

And I simply added a few `unchecked()` function calls to currently functioning code that has bounds checking already.

![image](https://user-images.githubusercontent.com/3761339/50524863-269a3500-0aa6-11e9-8fe8-c057419c7d13.png)

Is there something I'm missing?

https://github.com/jtenner/canvas-as/tree/uncheckedFillStyleOutOfBounds

I guess the only way to reproduce the problem is do this:

1. Clone the fork
2. npm install
3. npm start

**Comment by dcodeIO** [comment]
Note that using `unchecked` wouldn't result in an `unreachable` within the function right away (it really doesn't do any checks that could result in one), but would potentially corrupt memory somewhere else. So, what might have happened here is that the memory of `this` has become corrupted in code running earlier, which might itself have used `unchecked`. I suggest to add some `assert`s here and there to first try and figure out what's going on, because debugging memory issues like these the hard way is really time consuming.

**Comment by jtenner** [comment]
Definitely! I'll add some sanity checks here to see what's going on.

**Comment by MaxGraey** [comment]
You could use prefix increment instead all of this

**Comment by jtenner** [comment]
@MaxGraey that's exactly what I did. Thanks.
