### ISSUE TITLE
[Loader] Memory access

### ISSUE THREAD

**Issue by jnordberg** [AssemblyScript/assemblyscript#410]
The memory access helpers you get when instantiating module are great but is not usable in all cases, consider the following example:

assembly.ts
```ts
declare function print(message: string): void
print("Hello World!")
```

loader.ts
```ts
import * as fs from 'fs'
import * as loader from 'assemblyscript/lib/loader'
import Instance from './build/types'

const compiled = new WebAssembly.Module(fs.readFileSync(__dirname + '/build/untouched.wasm'))
const memory = new WebAssembly.Memory({initial: 1024})
const imports = {env: {memory}, assembly: {print}}
const instance = loader.instantiate(compiled, imports)

function print(ptr: number) {
    console.log(instance.getString(ptr))
}
```

Throws `ReferenceError: instance is not defined`.

Would be great if if the `getString` and other utils where exposed somewhere or that you could wrap the memory object prior to instantiating. E.g.

```ts
const compiled = new WebAssembly.Module(fs.readFileSync(__dirname + '/build/untouched.wasm'))
const memory = loader.memory({initial: 1024})
const imports = {env: {memory}, assembly: {print}}
const instance = loader.instantiate(compiled, imports)

function print(ptr: number) {
    console.log(memory.getString(ptr))
}
```

**Comment by dcodeIO** [comment]
Yeah, that's an issue when calling imports from within the WebAssembly `start` function where the module hasn't been fully initialized yet. The loader itself has `preInstantiate` and a `postInstantiate` routines for this with special code for dealing with memory (in a less efficient way) before instantiation is complete, but this also only works if memory is imported because an exported memory first becomes available when instantiation is complete.

One easy way to work around this for now is to declare an `export function main(): void {}` which essentially delays the statements that would normally go into the WebAssembly start function until the point `myModule.main()` is called manually.
