### ISSUE TITLE
Don't require all parameters of callback function for .map, .filter, etc.

### ISSUE THREAD

**Issue by vgrichina** [AssemblyScript/assemblyscript#449]
Most of the time someone uses `.map` they don't want to handle all arguments, but only first one, i.e. write code like this:
```ts
items.map(it => it.name);
```
Is it possible to implement in AssemblyScript using e.g. trampoline function of proper type passed to `.map` which will just passthrough throwing out extra args? Ideally compiler should also be able to inline whole construction into single loop in case when passed function is constant.

**Comment by willemneal** [comment]
I know this is not exactly what you're looking for and a bit ugly, but you could use underscores to ignore the other arguments.

```ts
let y = x.map<i32>((x:i32,_:i32,_:i32[]):i32 => x + 1);
```

**Comment by jtenner** [comment]
I would say write an inline function that uses unchecked property access. @vgrichina I can help you with this.

**Comment by dcodeIO** [comment]
There's also this Binaryen pass that might help: https://github.com/WebAssembly/binaryen/blob/master/src/passes/FuncCastEmulation.cpp

**Comment by MaxGraey** [comment]
I prefer solution without dynamic cast emulation. We could use syntactic sugar for this.
1. Inferring parametric type of array instance
2. resolve generic closure signature by type like
3. replace existing signature to polyfilled.

Example steps:
1. `arr.map(val => val)` --> `arr.map<i32[]>(val => val)`
2. `arr.map<i32[]>(val => val)` --> `arr.map<i32[]>((val: i32): i32 => val)`
3. `arr.map<i32[]>((val: i32): i32 => val)` --> 
    `arr.map<i32[]>((val: i32, _unused_$1: i32, _unused_$2: i32[]): i32 => val)`

**Comment by dcodeIO** [comment]
As an alternative solution, [the PR](https://github.com/AssemblyScript/assemblyscript/pull/514) linked above now explicitly compiles function expressions to match the context they are used in, in turn allowing us to infer parameter and return types and to omit any number of parameters in such cases.

It looks like this solves all cases mentioned in this issue, but the trampoline idea still remains valid in a scenario like

```ts
function foo(): void {}
arr.map(foo);
```

where a trampoline would be necessary to simply ignore excess arguments in order to make the call_indirect valid.
