### ISSUE TITLE
[Type Error] Null | Type must be cast after a conditional return

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#456]
Here is the working example: https://webassembly.studio/?f=zi21djvj57

Consider this example
```ts
function orNull(i: i32): Foo | null {
  if (i % 2 == 0)
  return null;
  return new Foo();
}

function example(): Foo | null {
  let x: Foo | null = orNull(1);
  if (x == null){
    return null;
  }
  return id(x); // x is not null, but compiler requires an explicit cast.
}

function id(f: Foo): Foo{
  return f;
}
```
Not sure how big of a problem this is since it might be better to enforce being explicit, but I thought I'd share it.  Also the same is true for if/else branches.

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) because this seems to be fixed meanwhile by extending null checks, at least when using `===`, with everything further being tracked in the respective issues dealing with changing the semantics of triple equals.
