### ISSUE TITLE
Feature: Targeting native code via LLVM for non-browser usage

### ISSUE THREAD

**Issue by otabekgb** [AssemblyScript/assemblyscript#458]
Targeting x86, ARM, Risc-V might be good for efficient non-browser applications like nodejs. Is there any plan for that?

**Comment by willemneal** [comment]
WebAssembly is in V8 so it is already can be used with nodejs.  Wasm is meant to be efficient to JIT so you should get close to native speed with node.  However, if you want it to be truly compiled to native code you could check out [cmm_of_wasm](http://simonjf.com/2018/08/27/cmm-of-wasm.html), an AOT compiler that uses Ocaml's IR to compile to native code.  However, the performance wasn't very good, but it was more of a proof-of-concept.  Personally I'd stick to node since it benefits from Google's V8 support and already has a lot of cool experimental features like threading.  Furthermore, there is [WAVM](https://github.com/AndrewScheidecker/WAVM/), which is a standalone JIT compiler that uses LLVM.

**Comment by Singha360** [comment]
@otabekgb 

[This might be of interest to you?](https://github.com/bytecodealliance/wasmtime/blob/master/docs/WASI-intro.md)

**Comment by munsocket** [comment]
V8 is additional layer, why not to support x86 directly?

**Comment by MaxGraey** [comment]
> V8 is additional layer, why not to support x86 directly?

WebAssembly target supports everywhere and will support cheap and uniform interop between any language and host via Interface types. Native targets via LLVM required a lot of efforts for implementation and support. It also will make toolchain more complicated. Probably we will support LLVM/LMIR codegen in future, but it's definitely not a priority right now.

**Comment by munsocket** [comment]
> You could use more simpler (lighter)

Only for simple examples that calculating numbers. But it’s complicated for me with something more difficult like audio/graphics support.

**Comment by Heath123** [comment]
These links might be interesting to people
https://github.com/WebAssembly/wabt/blob/main/wasm2c/README.md
https://github.com/turbolent/w2c2
https://github.com/dcodeIO/asc-native
https://github.com/vshymanskyy/wasm2native
