### ISSUE TITLE
Allow declare generics for function expressions

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#561]
```ts
var pass = <T>(a: T): T => a
```

**Comment by dcodeIO** [comment]
For a bit of background: I initially excluded this at the parser level because such a function isn't represented by a concrete value until fully resolved, so there's nothing to pass around, i.e. when calling a function with a generic function expression as an argument. To me it looks like it's rather a type than a function, and its existence is strictly tied to the dynamic nature of JS. Not saying "no" ofc, but that's the reasoning so far :)

**Comment by MaxGraey** [comment]
Btw this code also produce error:
```ts
var pass = <T>(a: T): T => a;
pass<i32>(1);
```
Output:
```
ERROR TS2304: Cannot find name 'T'.
```
and later:
```
ERROR TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'i32' has no compatible call signatures.
```

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) because it seems unlikely that we can solve this statically anytime soon due to a missing opportunity to represent it. If someone has an idea that doesn't involve costly runtime checks or otherwise including metadata, feel free to open a new issue or reopen this one.
