### ISSUE TITLE
WASI: Handling Signals and Events

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/assemblyscript#588]
Hello!

Looking at the [wasi bindings](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/bindings/wasi_unstable.ts#L1399), seems like there is some sort of ability to [subscribe to events](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/bindings/wasi_unstable.ts#L1399). I'm super interested in this, to do things like sleep and simply subscribe to a clock event. Is there a way to invoke callbacks in AS? Do we have any examples of this? 

Thanks! :smile:

**Comment by dcodeIO** [comment]
A callback in AS essentially is a typed function index. So if you do

```ts
function foo(fn: (a: i32) => i32): void {
  fn(1);
}
```

`fn` is a function index with a signature of `(i32): i32`, and when you call it a `call_indirect` with that signature and that function index is emitted. This also works if `foo` is exported and the function index is provided as an argument externally. If you get a runtime error when calling `fn`, that'd be because the signature doesn't match.

The same could also be written as

```ts
<i32>call_indirect(fn, <i32>1);
```

with the type assertions only necessary if contextual types differ.
