### ISSUE TITLE
WASI: Memory issues with allocators / Memory Leak / Crashing

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/assemblyscript#589]
Hello,

Been working on a fun little CLI project, to do [matrix rain effect](https://github.com/torch2424/wasm-matrix) using the wasi bindings, and using [wasa](https://github.com/jedisct1/wasa).

I'm using [Wapm / Wasmer](https://wapm.io/help/guide) to run my Wasm module.

I'm using the "allocator/arena", as it is the one suggested by Wasa. I tried the other two allocators (tlsf and buddy), but they immediately crash when trying to instantiate an object it seems. And everything works using arena, however, after a short while, the program simply crashes, with a Memory out of Bounds error.

```
thread 'main' panicked at 'wasm trap occured: memory out-of-bounds access', src/bin/wasmer.rs:359:51
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

If you open up `htop`, you will also notice the memory infinitely grows. And I double checked to make sure all memory manually allocated, is manually freed. And a static number of objects are created / recycled.

**So my questions are:**

1. Why don't the tlsf and buddy allocators work?
2. How can I fix this memory leak / crash? Is it an Assemblyscript issue, or a Wasmer issue?

Thanks! :smile:

**Comment by dcodeIO** [comment]
It is likely that both tlsf and buddy have some remaining issues (I tend to use tlsf because buddy's upfront setup seems suboptimal, but I recently also discovered some issues it has related to growing memory). Immediately throwing on the first `new` seems odd, though, and could either be related to dealing with `memory.grow` on the VM side or be some sort of memory corruption on the AS side.

For a bit of background: All the allocators, incl. arena, have in common that they try to double the number of pages when running out of memory. For that, each module starts with an initial amount of pages that fits static data, but doesn't define a maximum number of pages so growing can happen until the host runs out of memory or otherwise prevents the module from growing pages if it has its own internal maximum. Afaik browsers cap at around 2GB or so, which allocators detect and then grow by the actually necessary amount of pages instead. If that's not possible as well, an `unreachable` occurs.

**Comment by jedisct1** [comment]
https://github.com/jedisct1/was-not-wasm may help you debug memory corruption issues.

**Comment by torch2424** [comment]
@dcodeIO

Ahh makes sense. Yeah I think I'm hitting wasmers Max, as it grows to about 4GB after a while. 

I'll see if I can get tlsf working. Perhaps I can mess around with some things :)

If I may ask, what's my best plan of action here? Since I'm depending on Wasa, and it seems like a lot of the bindings cant really be statically bound. And I think I would need strings here, which I assume are also dependant on the allocator?

@jedisct1

Rad, thanks for that! I'll check that out if I find the time! Also, thanks for making Wasa! Super rad! If you have any suggestions as well it would be super helpful! 😀
