### ISSUE TITLE
[wiki todo] Update wiki on use of allocators, and how each one works.

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#613]
Unless I missed it, I didn't see in the wiki a description of allocators and recommendation of which ones to use.

The obvious place for it would be in the "Memory" page.

If this info is already in the wiki, maybe it just needs some re-organization to make it obvious where to find it.

**Comment by MaxGraey** [comment]
I guess this not actual anymore. When new runtime will shipped all necessary information exists here:
https://github.com/AssemblyScript/assemblyscript/wiki/Runtime

**Comment by trusktr** [comment]
Ah, okay. So runtime is the new way to choose allocators (among others). Just curious, why no using `import` anymore for this? Is it because `import` was too restrictive?

**Comment by dcodeIO** [comment]
One reason is that memory manager and garbage collector are interleaved now, so you really pick an implementation of the entire runtime interface. Providing reasonable defaults also allows users to get started more quickly, instead of learning about memory managers right at the start of their journey.

**Comment by trusktr** [comment]
Cool. I'll update the Wiki when I get a chance.

**Comment by trusktr** [comment]
Closing, as the new docs.assemblyscript.org has info on the new stuff.
