### ISSUE TITLE
comparing strings (difference between == and ===)

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#621]
I'm trying to write some code using `assert`:

```ts
	assert(
		s.toString() === '{W: 20.0, H: 30.0}',
		'toString should be "{W: 20.0, H: 30.0}". Got: "' + s.toString() + '"'
	)
```

and the assert fails with output showing that the strings are equal (despite failing):

```
toString should be "{W: 20.0, H: 30.0}". Got: "{W: 20.0, H: 30.0}"
```

As far as I can tell, the strings look identical (I copy and paste them into JS console, and `===` shows true).

But if I try to use `==`, then I get a runtime error:

output from my abort function:

```
msg: 0 <-- assert() call in rt/pure.ts has no message
 file: ~lib/rt/pure.ts
 line: 115
 col: 13
```

Error in console:

```
Uncaught (in promise) RuntimeError: unreachable
    at wasm-function[19]:41
    at wasm-function[20]:14
    at wasm-function[41]:365
    at wrap (http://127.0.0.1:8080/js/as-loader.js:250:12)
    at runGlas (http://127.0.0.1:8080/ts/index.js:68:9)
```

<img width="412" alt="Screen Shot 2019-05-29 at 8 35 02 AM" src="https://user-images.githubusercontent.com/297678/58570374-b9bdcf00-81ec-11e9-910f-781ed1dabcf0.png">

How should I compare the strings?

**Comment by MaxGraey** [comment]
`===` - is compare references. Don't use this especially for strings
`==` - usual way for compare and trigger overloaded method for string comparision.
This one of things which different compare to JS?TS

**Comment by trusktr** [comment]
Why might I get that error when trying to use `==`?

Also what about portability? Seems like this difference between JS and TS loosens the strictness on the JavaScript side.

**Comment by trusktr** [comment]
Maybe `==` and `===` should be implemented so they meet expectations?

It's super nice strings are references in AS now, but I think the expectation here may be important from a DX perspective (well, assuming we're considering what happens when AS gets more popular, and people who may not necessarily know JS/TS even that well, will jump onto AS with certain expectations (but I do think that the current version is 'better' from a pure language perspective)).

**Comment by trusktr** [comment]
I keep running into JS code like

```js
		this.width === other.width && this.height === other.height
```

that I have to convert to

```ts
		this.width == other.width && this.height == other.height
```

which feels odd to some degree because of existing JS/TS habits. 

Could it be a source of confusion?

And also, code portability (imagine a module that runs in both AS and TS, but the TS also compiles to plain JS for users that consume the library in plain JS projects).

**Comment by dcodeIO** [comment]
Doesn't `===` do the same as `==` for numeric values?

**Comment by trusktr** [comment]
Oh, it does? That can be another source of confusion between JS/TS and AS.

**Comment by MaxGraey** [comment]
Tripple equal doesn't any sense in AS, because all types already strictly typed. So `===` using for special meaning (actually for exact reference comparision)

**Comment by dcodeIO** [comment]
Copying from the new docs:

AssemblyScript uses `===` for identity comparisons (means: the exact same object). Idea is that its special JavaScript semantics for strings (same type and value) become irrelevant in a strict type context anyway. Some like this better, some hate it for portability reasons.

```ts
var s1 = "1";
var s2 = "123".substring(0, 1);
s1 === s1 // true
s1 === s2 // false
s2 === s2 // true
s1 === 1 // compile error
s1 == s2 // true
```

Maybe adding:

```ts
1 === 1 // true
1 == 1 // true
```

Really only relevant for strings and possibly operator-overloaded objects.

**Comment by dcodeIO** [comment]
Btw, the new docs are not finished yet, but if you are interested: https://docs.assemblyscript.org

**Comment by paul-go** [comment]
@MaxGraey 
I've been following this project since you posted a message on [the thread I started](https://github.com/Microsoft/TypeScript/issues/9202) on the TypeScript forum. I think AssemblyScript's  handling of `==` and `===` is a potentially disastrous language design mistake.

The majority of high quality JS/TS code I've seen used `===` exclusively and often forbids the use of `==` via linting rules. By making `===` something for identity comparisons, you've basically broken compatibility with a _very_ large set of pre-existing TypeScript code. Possibly the case could be made that compatibility with existing code isn't specifically a goal, but the ability to build libraries that are written with a more aggressively typed version of TypeScript, and have these libraries run as WebAssembly or as JS is IMO the main selling point of AssemblyScript.

Because there's no parallel to primitive identity comparisons in TS, this should involve the use of a new operator such as `equals` or `eq` or even `====`, because any code base that requires primitive identity comparisons isn't going to run in JS anyways, and so compatibility with JS would be an explicit non-goal for this code. Or, if parse compatibility with TS is a goal for some reason, I think some top-level global function like `equals(a, b)` would be better.

At a minimum, I would reverse the behavior of `==` and `===`. People get fired for using `==` in JS.

(All this is from the perspective of a person who may have fairly strong grasp of language design, but doesn't claim to know much about AssemblyScript internals & challenges)

**Comment by dcodeIO** [comment]
Btw, the docs have a mention of the [=== behavior](https://docs.assemblyscript.org/basics#the-case-of) that might help to clarify the design decision a bit. It's still unfortunate of course and we might want to do something about it, but the reasoning isn't completely off as well.

**Comment by GirkovArpa** [comment]
> @MaxGraey
> By making `===` something for identity comparisons, you've basically broken compatibility with a _very_ large set of pre-existing TypeScript code.

Can this be solved with a simple search and replace?
