### ISSUE TITLE
Array of bools is not allowed in new runtime

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#650]
```
ERROR AS200: Conversion from type 'i32' to 'bool' requires an explicit cast.

     return element; // no need to retain -> is moved
            ~~~~~~~
 in ~lib/array.ts(290,11)
```

**Comment by dcodeIO** [comment]
Ah, issue here is on line

```ts
var element = load<T>(this.dataStart + (<usize>(--length) << alignof<T>()));
```

Here, the type for `element` is inferred, starting by assuming `i32`, and `load<bool>` will try to load to the target type. Currently, the fix is

```ts
var element: T = load<T>(...)`
```

but there really should be something better. One thought I had was to have a contextual flag for `RETAIN_TYPE` as an alternative, that the `load` built-in could use to detect such cases.

**Comment by dcodeIO** [comment]
Should have been fixed by the commit linked above. Feel free to reopen if necessary!
