### ISSUE TITLE
Arrow functions not exported

### ISSUE THREAD

**Issue by andykais** [AssemblyScript/assemblyscript#675]
Not sure if this has been covered in another issue (#517 or #661) but I exported an arrow function alongside a `function` function, but the anonymous function was not picked up by the exports.
The problem is described here: https://webassembly.studio/?f=qplh58m371
The working function is `add` and the not found function is `divide`

**Comment by dcodeIO** [comment]
```ts
export const divide = (x: number, y: number): number => {
  return x / y
}
```

What this does is create an anonymous function, add it to the webassembly table, assigning its index in the table to the variable `divide`. Externally, the `divide` export is a function table index that can be called if there is another export:

```ts
export function call_it(fn: (x: number, y: number) => number, x: number, y: number): number {
  return fn(x, y);
}
```

Now, doing the following externally will call `divide` and return the result:

```js
module.call_it(module.divide, 1, 2);
```

**Comment by andykais** [comment]
hmm I see how this works, but why is it designed this way? The type signature tells you that it is a function, but it behaves differently than a es5 function by default. Is it because of the assignment step?

**Comment by dcodeIO** [comment]
If there is a "why" to this than it is that the compiler tries to stay true to the input, and the input is an assignment, yeah. If the modifier wasn't `const` but `var`, that's also the only sensible thing a static compiler can do.

**Comment by MaxGraey** [comment]
@dcodeIO I guess will be great describe this behaviour in docs. wdyt?

**Comment by dcodeIO** [comment]
Btw, I wondered a bit about the expectation here. Is there special semantics defined for this case (like, in the specification) that I am not aware of or does it rather "just so happen" (because `const`) to work as if it was declared like a normal named function in modern JS engines?

**Comment by MaxGraey** [comment]
Hmm, good question

**Comment by duncandean** [comment]
Also ran into this peculiarity. Makes sense because it's an assignment. Looking at the `.wat` helped.

What I found quite interesting  is that without a declared function like `call_it()` above, we get this `untouched.wat`:

```wat
(module
 (type $i32_i32_=>_i32 (func (param i32 i32) (result i32)))
 (memory $0 0)
 (table $0 2 funcref)
 (elem (i32.const 1) $start:assembly/index~anonymous|0)
 (global $assembly/index/add i32 (i32.const 1))
 (export "memory" (memory $0))
 (export "add" (global $assembly/index/add))
 (func $start:assembly/index~anonymous|0 (; 0 ;) (param $0 i32) (param $1 i32) (result i32)
  local.get $0
  local.get $1
  i32.add
 )
)
```

The `add()` function code actually exists, but once optimized, we have:

```wat
(module
 (memory $0 0)
 (global $assembly/index/add i32 (i32.const 1))
 (export "memory" (memory $0))
 (export "add" (global $assembly/index/add))
)
```

It basically just keeps the index. Everything else is purged since I suppose there is no function that can be a caller of `add()`.

Just found that interesting. 🙂 I assume it is a `wasm-opt` thing?

**Comment by MaxGraey** [comment]
> Just found that interesting. 🙂 I assume it is a wasm-opt thing?

By default AS don't export tables because it prevent some major optimization like devirtualization / directize. But you could turn it on via "--exportTable" flag:

https://webassembly.studio/?f=exqlp274tku

now it produce expected result even with optimizations:
```wat
(module
  (type $t0 (func (param i32 i32) (result i32)))
  (func $f0 (type $t0) (param $p0 i32) (param $p1 i32) (result i32)
    get_local $p0
    get_local $p1
    i32.add)
  (table $table (export "table") 2 anyfunc)
  (memory $memory (export "memory") 0)
  (global $add (export "add") i32 (i32.const 1))
  (elem (i32.const 1) $f0)
)
```
@dcodeIO I guess need some warning and force `--exportTable` if some one export indirect functions like that.

**Comment by duncandean** [comment]
Ah. Thanks for clearing that up 😄

**Comment by MaxGraey** [comment]
Btw thank you for noticing that issue
