### ISSUE TITLE
Use a class "by value"

### ISSUE THREAD

**Issue by geloizi** [AssemblyScript/assemblyscript#688]
Does AssemblyScript supports using classes "by value" to make structures binary compatible between AssemblyScript and C++? I.e., what would be an AssemblyScript equivalent to:

```
struct {
    int x;
    struct { int y; } z;
}
```

Also I noticed that `sizeof<AnyClass>()` always returns `4`. Is this by design?

**Comment by MaxGraey** [comment]
`sizeof<AnyClass>()` return `4` because AS return size of pointer which is always `4` bytes in wasm32. if you want retrieve size of structure you should use `offsetof<AnyClass>()`

**Comment by geloizi** [comment]
> you should use `offsetof<AnyClass>()`

confirmed

**Comment by geloizi** [comment]
What about using a class "by value"?

**Comment by dcodeIO** [comment]
The language doesn't provide this on its own (always passes by reference by design), but something along these lines can be achieved through manual offset calculation ([see](https://docs.assemblyscript.org/details/interoperability#class-layout)). A helper like [this pointer experiment](https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/std/pointer.ts) might also help.

**Comment by geloizi** [comment]
I think "inline structs" is a valuable feature that makes AssemblyScript binary compatible with other languages. Do you think it could be added the language? May be with a decorator.

**Comment by MaxGraey** [comment]
I don't think this necessary feature. AS will support tuples when multi-value proposal landed.
Currently you could use something like this:
```ts
class {
  x: i32;
  z_x: i32; // equivalent to `struct { int x, int y, int z } z`
  z_y: i32;
  z_z: i32;
}
```
