### ISSUE TITLE
[Feature request] Add REPL

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#699]
It will be nice to have REPL with history and minimal environment. I guess we could reuse some urils from node.js like "repl" module:
```js
const Repl  = require('repl');

const repl = Repl.start({
  prompt: 'assemblyscript> ',
  useColors: true,
  ignoreUndefined: true
});

repl.on('line', line => {
   line = line.trim();
   // try compile assemblyscript for this line here
});
```

**Comment by dcodeIO** [comment]
Since we are talking about a static compiler here that cannot evaluate an additional line ad-hoc, it looks like the only way this can be done is to keep a complete history of the input (discarding invalid input) and recompile everything with a new line added, including any variable assignments, function calls etc. This might work somehow, but I wonder if it's a good match due to compile time delay.

**Comment by MaxGraey** [comment]
I guess it possible. For example Rust has some unofficial crates for this. Like [evcxr_repl](https://github.com/google/evcxr/blob/master/evcxr_repl/README.md) and [runner](https://github.com/stevedonovan/runner). Also see [RFC proposal](https://github.com/rust-lang/rfcs/issues/655).
