### ISSUE TITLE
Option to construct Array from data pointer and length

### ISSUE THREAD

**Issue by singpolyma-shopify** [AssemblyScript/assemblyscript#711]
It would be nice to have a safe API to construct an array from a data pointer and length.  The biggest obstacle I see to this is that the `data` member of ArrayBufferView should be a valid ArrayBuffer rather than unmanaged memory.  If the value can be "frozen" somehow to prevent any attempts at modification, and if the API does not rely on reading the ArrayBuffer length field, then I think this could be done.

**Comment by dcodeIO** [comment]
Have you looked at the recent addition of the `TypedArray#wrap` implementations in https://github.com/AssemblyScript/assemblyscript/pull/695? I think that does about what you are looking for, except that it really can't be just a pointer if the API is supposed to be somewhat safe in a manged sense.

**Comment by singpolyma-shopify** [comment]
The `wrap` functions don't work for me for two reasons: one is that they still take an `ArrayBuffer` and I don't have one (just unmanaged memory being passed in) and two: I'm using much more interesting types (unmanaged classes, etc) than just primitives.

**Comment by MaxGraey** [comment]
If you work with raw pointers and just want have more sophisticated interface or wrapper you may find it useful: https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/std/pointer.ts

**Comment by dcodeIO** [comment]
So regarding

> If the value can be "frozen" somehow to prevent any attempts at modification

I think that the only way to do this is to copy the region of unmanaged memory to a managed object, since the pointer might come from something that has not been allocated by the runtime itself. In general, wrapping a random region of memory in an ArrayBuffer has to be considered unsafe because the region might be managed memory, with runtime information, and modifying that would break the module.

Now it looks like this is not possible currently in a safe way (as of the proposed --unsafe flag), but might become possible by implementing something along the lines of `ArrayBuffer.from` (not sure about the name) that takes a pointer and a length, copies (!), and makes a managed ArrayBuffer of it that can be safely modified. Would that help in your use case?

**Comment by singpolyma-shopify** [comment]
I understand that to be safe under all circumstances it would have to copy.  That's something I could implement now with no issue if I wanted to copy.

By "frozen" I mean within assemblyscript.  Outside changes would not be a problem because (a) they don't happen in my case and (b) they would be under my control if they did.

I probably should not have used the word "safe" in my OP.  Of course there are ways that doing what I want would be unsafe in some cases.  What's really preventing me from just doing this right now (I currently use a `Slice` class that is like an Array in interface but is an unmanaged class instead) is that if I hand some code an Array and that code calls `push` or similar then very crazy things could happen (since uninitialized memory would be read to determine the ArrayBuffer size and then the ArrayBuffer might be "resized" and I'm really not sure what would happen).

Of course, It's very likely the answer is "don't do that" but it seemed to me that there was a chance it could be made "safe" *for my case* (not in general) if an array could be marked as frozen or similar and thus not use the ArrayBuffer as anything but a pointer.

**Comment by dcodeIO** [comment]
I see. In order to implement the Array interface, there must be a `length` available somehow because otherwise it can't function according to the Array interface. For instance, one can't `.push` to such an array without knowing the insertion index (current length).

Instead, you might be interested in the [pointer experiment](https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/std/pointer.ts) linked by Max earlier. This one does about what you are trying to accomplish by allowing to access sequential values at a random address by means of indexed access.

```ts
var myPtr = new Pointer<i32>(ptr);
myPtr[0];
myPtr[1];
```

Here, if `ptr` is `8`, `myPtr[0]` accesses the `i32` at `8`,`myPtr[1]` accesses the `i32` at `12` etc. It's not in the standard library (yet) since it originated as an experiment for a zero-cost pointer abstraction.

If you decide to give it a try, let me know if it works for you and where it can be improved.

**Comment by singpolyma-shopify** [comment]
Yes, the `Pointer` is interesting.  It's similar to the `Slice` that I use now, but it doesn't have length so can't be iterated over, etc, and of course still has to be copied if I have code that wants an `Array`.

I'll keep things separate for now and keep requiring a copy to get an `Array`. I'll keep thinking and see if I come up with more later :)
