### ISSUE TITLE
[Question] ASM.js mangled names

### ISSUE THREAD

**Issue by lbittner-pdftron** [AssemblyScript/assemblyscript#795]
Hello!

I created a fork of this project to update Binaryen so I can produce a proper ASM.js file, which is working okay.

I've noticed that the exported function names are all mangled (which i'm assuming the WASM file does as well - except the loader handles it).

Is the loader supposed to be able to handle ASM modules as well? Ive tried running the ASM module through `loader.demangle` but it doesn't seem to do anything.

Any help is appreciated. Thanks!

**Comment by MaxGraey** [comment]
Additional parameter only appear for exported methods with optional arguments. This first argument actually is number of non-optional params (`argc`) and setup by `__setargc` before call. It should handle by loader in [this part](https://github.com/AssemblyScript/assemblyscript/blob/master/lib/loader/index.js#L342)

**Comment by dcodeIO** [comment]
What happens here is that Binaryen mangles the names of JS variables and functions that would otherwise be invalid. My expectation would be that this doesn't affect export names, though, but this might have changed with Binaryen moving to ES6 modules or something recently. Need to check.

Regarding

```ts
function MyClass_test($0, $1)
```

If that's a function `MyClass#test`, then `$0` is the `this` argument, which is the memory address of the respective `MyClass` instance the method is called upon, followed by the actual function parameters. All instance methods, including constructors, do this. The only case where supplying `0` as the `this` argument is valid is when calling a constructor, as this tells the ctor to allocate on its own instead of reusing memory allocated by a subclass.

**Comment by dcodeIO** [comment]
Binaryen issue on export names: https://github.com/WebAssembly/binaryen/issues/2310
