### ISSUE TITLE
Get pointer from instance in JS

### ISSUE THREAD

**Issue by yourheropaul** [AssemblyScript/assemblyscript#817]
If I have an instance of a class defined in WASM and instantiated in JavaScript, is there any way to get its address? The loader unit tests [suggest that it's possible](https://github.com/AssemblyScript/assemblyscript/blob/master/lib/loader/tests/index.js#L150), but I can't replicate it.

For example (from that test):

```typescript
var car = new module.Car(5);
//...
module.__release(car); // uses Car.prototype.valueOf to obtain `thisPtr`
```

How does `__release()` get `thisPtr`? Is there some way of extracting is programmatically?

**Comment by willemneal** [comment]
In your example, the loader will wrap all of the exported methods so that you get a JS object instead of getting the pointer and then calling them each e.g. `module.Car_run(car)`. 

To access the pointer you can use the prototype function e.g. `car.valueOf()`.  Which gets called when you pass it to `__release()`.

One word of caution if you are inspecting the pointers: they are byte addressed, so if you are trying to read a 32 byte address you have to shift it to the right twice.
