### ISSUE TITLE
Linking

### ISSUE THREAD

**Issue by jcampbell05** [AssemblyScript/assemblyscript#84]
I want to use this to link it against a C program, is there a way to do this so a function in my C code can be called from the WASM ?

**Comment by dcodeIO** [comment]
At this point you could use a tool like Binaryen's `wasm-merge`. It essentially resolves the imports of one module to the exports of another. In case plain merging doesn't work, for example because two memory managers get into each other's way, something similar can be achieved by simply using two wasm files, providing the exports of the first as the imports of the second (or, somewhat more complicated, import the memory manager of the first as exported in the second prior to merging).

There'll be additional choices in the future, for example once [DynamicLinking](https://github.com/WebAssembly/tool-conventions/blob/master/DynamicLinking.md) matures. There's also the pending idea to use a module compiled using another toolchain as the "base image" of an AssemblyScript module, basically appending AS-generated code to the base module while using a `.d.ts` to describe the functionality provided by it (not yet implemented, though).

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
