### ISSUE TITLE
is wasm-module in alignment with some of our goals?

### ISSUE THREAD

**Issue by richardanaya** [AssemblyScript/assemblyscript#937]
Hey all, i'm a web assembly nerd over in Rust land, and I created this technology agnostic libary that really helps me.

https://github.com/richardanaya/wasm-module

I know very little about assemblyscript's initiatives or goals, but I think the tech I use in js_ffi could accelerate you all a bit.

https://github.com/richardanaya/js_ffi/

Basically its just a very generic methodology for communicating from web assembly to javascript (browser or node) and it requires no code generation.

I'd love to know if there is any interest in creating a library to support this type of component.  Maybe I can help in some way.

**Comment by dcodeIO** [comment]
Welcome to AssemblyScript land :)

From a quick glimpse it seems that one important difference here is string layout, which is (potentially ill-formed) UTF16-LE in AS. Other than that I think that the inner workings are similar enough due to compiling to WebAssembly that it should "just work". Would certainly be useful!

Implementation-wise we have [the loader](https://github.com/AssemblyScript/assemblyscript/tree/master/lib/loader), which is what most people use today, and `declare`d [imports](https://docs.assemblyscript.org/basics/exports-and-imports#imports) to JS glue one can call.
